bcgov/fin-pay-transparency

.github/workflows/schemaspy.yml

schemaspy.yml

---

frontend/src/components/Dashboard.vue

https://finrms.atlassian.net/browse/GEO-57
changed existing employee count text field to a combobox.

GEO-57 - Change employeeCount to combobox

---

charts/fin-pay-transparency/values.yaml

fixing deployment issue

---

backend/src/app.ts
backend/src/server.ts
backend/src/v1/routes/auth-routes.ts

fix: sonar fixes.

---

backend/package.json
backend/src/app.spec.ts
backend/src/v1/prisma/schema.prisma
backend/src/v1/routes/code-routes.ts
backend/src/v1/services/code-service.spec.ts
backend/src/v1/services/code-service.ts

https://finrms.atlassian.net/browse/GEO-74

GEO-73: GET API for NAICS Code

---

frontend/src/components/Header.vue
frontend/src/components/Login.vue
frontend/src/components/Logout.vue
frontend/src/components/TokenExpired.vue

https://finrms.atlassian.net/browse/GEO-121
---
- [Frontend](https://pay-transparency-pr-77-frontend.apps.silver.devops.gov.bc.ca)

Bugfix/Fix sonar error unsanitized string in href GEO-121

---

frontend/src/components/Header.vue
frontend/src/components/Login.vue
frontend/src/components/Logout.vue
frontend/src/components/TokenExpired.vue

reverting as it is not working.
---
- [Frontend](https://pay-transparency-pr-79-frontend.apps.silver.devops.gov.bc.ca)

Revert "Bugfix/Fix sonar error unsanitized string in href GEO-121 (#77)"

---

frontend/src/components/InputForm.vue

Slight change to frontend error messages shown in response to CSV validation errors
Fixes # [(issue)](https://finrms.atlassian.net/browse/GEO-137)
- Visual inspection only.  No new unit tests.
---
- [Frontend](https://pay-transparency-pr-83-frontend.apps.silver.devops.gov.bc.ca)

changed error message related to CSV validation

---

frontend/src/components/Header.vue
frontend/src/components/Logout.vue
frontend/src/components/TokenExpired.vue
frontend/src/main.js

https://finrms.atlassian.net/browse/GEO-124
---
- [Frontend](https://pay-transparency-pr-85-frontend.apps.silver.devops.gov.bc.ca)

Bugfix/Logout Grammar GEO-124

---

frontend/src/components/Header.vue
frontend/src/components/Login.vue
frontend/src/components/Logout.vue
frontend/src/components/TokenExpired.vue

---
- [Frontend](https://pay-transparency-pr-86-frontend.apps.silver.devops.gov.bc.ca)

fix: Fixing sonar hotspot

---

.github/workflows/ci_cd_on_pr_dev_sandbox.yml
backend/src/v1/services/validate-service.spec.ts
backend/src/v1/services/validate-service.ts

Fixed a bug introduced by the last PR.  
- Existing tests pass + manual test via submitting a sample CSV through the web app
---
- [Frontend](https://pay-transparency-pr-92-frontend.apps.silver.devops.gov.bc.ca)

moved the seven different column name constants into an enum

---

charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-97-frontend.apps.silver.devops.gov.bc.ca)

chore: enable pgbouncer

---

frontend/src/components/InputForm.vue

https://finrms.atlassian.net/browse/GEO-148
---
- [Frontend](https://pay-transparency-pr-102-frontend.apps.silver.devops.gov.bc.ca)

Bugfix/Change text to Employer GEO-148

---

backend/src/app.ts

---
- [Frontend](https://pay-transparency-pr-112-frontend.apps.silver.devops.gov.bc.ca)

fix: winston

---

frontend/src/components/InputForm.vue

https://finrms.atlassian.net/jira/software/projects/GEO/boards/70?selectedIssue=GEO-149&text=149
It works better now and clears errors upon clicking submit with a good CSV file. 
---
- [Frontend](https://pay-transparency-pr-111-frontend.apps.silver.devops.gov.bc.ca)

Feature/Move error reporting and clear file upon error GEO-149

---

backend/src/app.ts
backend/src/config/index.ts
charts/fin-pay-transparency/charts/backend/templates/deployment.yaml

---
- [Frontend](https://pay-transparency-pr-129-frontend.apps.silver.devops.gov.bc.ca)

feat: add rate limiting to backend

---

backend/db/migrations/V1.0.9__drop_input_data.sql
backend/src/v1/prisma/schema.prisma

https://finrms.atlassian.net/jira/software/projects/GEO/boards/70?selectedIssue=GEO-151&text=151
---
- [Frontend](https://pay-transparency-pr-130-frontend.apps.silver.devops.gov.bc.ca)

drop data input table and generate schema.prisma

---

.github/dependabot.yml

Removing Dependabot as we have Renovate now.
---
- [Frontend](https://pay-transparency-pr-140-frontend.apps.silver.devops.gov.bc.ca)

chore: removed dependabot

---

.github/workflows/.deploy.yml

do fresh install all the time for PR deployments.
it is now uninstall first, install after
https://github.com/bcgov/fin-pay-transparency/actions/runs/7483999036/job/20370148729#step:4:128
---
- [Frontend](https://pay-transparency-pr-150-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-150-frontend.apps.silver.devops.gov.bc.ca)

fix(helm): do fresh install for sandbox deploys.

---

backend/src/app.ts
backend/src/v1/services/file-upload-service.ts
backend/src/v1/services/report-calc-service.ts
backend/src/v1/services/report-service.ts
backend/src/v1/services/utils-service.ts

1. Add Logger middleware to log url, method and correlation ID
2. Add some more logs to file upload
3. Add axios interceptors logs
---
- [Frontend](https://pay-transparency-pr-153-frontend.apps.silver.devops.gov.bc.ca)

feat: logs and middleware

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/ci_cd_on_pr_dev_sandbox.yml
.github/workflows/cleanup-on-pr-close.yml
.github/workflows/sysdig.yml
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/charts/frontend/templates/deployment.yaml
charts/fin-pay-transparency/charts/frontend/templates/service.yaml
charts/fin-pay-transparency/values.yaml
frontend/Caddyfile
sysdig/sysdig.yml

1. Added prometheus scraping toenable prometheus integration with sysdig
2. Added github workflow to deploy sysdig setup to tools environment
3. Added sysdig folder with sysdig yaml for adding users to sysdig.
https://finrms.atlassian.net/browse/GEO-185
---
- [Frontend](https://pay-transparency-pr-156-frontend.apps.silver.devops.gov.bc.ca)

feat: prometheus and sysdig

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/ci_cd_on_pr_dev_sandbox.yml
.github/workflows/cleanup-on-pr-close.yml
.github/workflows/sysdig.yml

---
- [Frontend](https://pay-transparency-pr-162-frontend.apps.silver.devops.gov.bc.ca)

fix: sysdig path

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
charts/fin-pay-transparency/charts/backend/templates/pdb.yaml
charts/fin-pay-transparency/charts/doc-gen-service/templates/pdb.yaml
charts/fin-pay-transparency/charts/frontend/templates/pdb.yaml

---
- [Frontend](https://pay-transparency-pr-166-frontend.apps.silver.devops.gov.bc.ca)

fix: pdb issue

---

.github/workflows/ci_cd_on_pr_dev_sandbox.yml

GitHub Actions for PR pipeline is updated for the quota check.
---
- [Frontend](https://pay-transparency-pr-167-frontend.apps.silver.devops.gov.bc.ca)

fix(GHA): PR deploy quota check

---

renovate.json

fixed:  WARN: Config needs migrating coming from:- https://github.com/bcgov/fin-pay-transparency/actions/runs/7608217713/job/20716955375#step:3:77

fix(renovate): update configuration to get rid of warnings

---

backend/src/app.ts
backend/src/v1/routes/code-routes.ts
backend/src/v1/routes/file-upload-routes.ts
backend/src/v1/routes/report-routes.ts
backend/src/v1/routes/user-info-routes.ts

Used a global middleware in app.ts for all the routes which removes the necessity of duplicating code in routes for session and backend token check.
---
- [Frontend](https://pay-transparency-pr-173-frontend.apps.silver.devops.gov.bc.ca)

refactor: change the code to remove duplication in routes.

---

.github/workflows/unittests.yml
renovate.json

---
- [Frontend](https://pay-transparency-pr-177-frontend.apps.silver.devops.gov.bc.ca)

fix: renovate config and add ignore for unit tests

---

backend/src/app.spec.ts
backend/src/app.ts
backend/src/v1/prisma/prisma-client.ts
charts/fin-pay-transparency/charts/backend/templates/deployment.yaml

---
- [Frontend](https://pay-transparency-pr-199-frontend.apps.silver.devops.gov.bc.ca)

feat(backend): health check to include database connection check GEO-247

---

backend/src/v1/routes/report-routes.ts
backend/src/v1/services/report-service.spec.ts
backend/src/v1/services/report-service.ts
backend/src/v1/services/utils-service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/common/__tests__/apiService.spec.ts
frontend/src/common/apiService.ts
frontend/src/utils/constant.js

https://finrms.atlassian.net/browse/GEO-200
---
- [Frontend](https://pay-transparency-pr-195-frontend.apps.silver.devops.gov.bc.ca)

feature/Add api to get report GEO-200

---

backend/src/v1/routes/report-routes.ts
backend/src/v1/services/report-service.spec.ts
backend/src/v1/services/report-service.ts
backend/src/v1/services/utils-service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/common/__tests__/apiService.spec.ts
frontend/src/common/apiService.ts
frontend/src/utils/constant.js

Reverts bcgov/fin-pay-transparency#195
---
- [Frontend](https://pay-transparency-pr-205-frontend.apps.silver.devops.gov.bc.ca)

Revert "feature/Add api to get report GEO-200"

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml
.github/workflows/schemaspy.yml

---
- [Frontend](https://pay-transparency-pr-208-frontend.apps.silver.devops.gov.bc.ca)

fix: pipeline issue

---

.github/workflows/unittests.yml

**What changed**
Adding the sonar token to the github actions workflows
---
- [Frontend](https://pay-transparency-pr-211-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-211-frontend.apps.silver.devops.gov.bc.ca)

adding doc gen service sonar token

---

.gitignore
backend/src/constants/index.ts
backend/src/logger.ts
backend/src/v1/routes/auth-routes.spec.ts
backend/src/v1/routes/auth-routes.ts
backend/src/v1/routes/code-routes.spec.ts
backend/src/v1/routes/file-upload-routes.spec.ts
backend/src/v1/routes/report-routes.ts
backend/src/v1/routes/user-info-routes.spec.ts
backend/src/v1/services/report-service.ts
doc-gen-service/src/server.ts
doc-gen-service/src/v1/services/doc-gen-service.ts

Improving logging in the backend
---
- [Frontend](https://pay-transparency-pr-222-frontend.apps.silver.devops.gov.bc.ca)

Geo 181 improve logging in backend doc gen api

---

charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-232-frontend.apps.silver.devops.gov.bc.ca)

Updated memory allocation

---

charts/fin-pay-transparency/charts/backend/templates/deployment.yaml
charts/fin-pay-transparency/charts/backend/templates/is.yaml
charts/fin-pay-transparency/charts/database/templates/deployment.yaml
charts/fin-pay-transparency/charts/database/templates/is.yaml
charts/fin-pay-transparency/charts/doc-gen-service/templates/deployment.yaml
charts/fin-pay-transparency/charts/doc-gen-service/templates/is.yaml
charts/fin-pay-transparency/charts/frontend/templates/deployment.yaml
charts/fin-pay-transparency/charts/frontend/templates/is.yaml

---
- [Frontend](https://pay-transparency-pr-235-frontend.apps.silver.devops.gov.bc.ca)

feat(CI): imagestreams, make it conditional and use artifactory

---

frontend/src/components/Dashboard.vue

https://finrms.atlassian.net/browse/GEO-329
---
- [Frontend](https://pay-transparency-pr-238-frontend.apps.silver.devops.gov.bc.ca)

fix "View" button not working

---

.github/workflows/ci_cd_on_pr_dev_sandbox.yml

---
- [Frontend](https://pay-transparency-pr-240-frontend.apps.silver.devops.gov.bc.ca)

fix(GHA)!: PR Pipeline tagging

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml

---
- [Frontend](https://pay-transparency-pr-242-frontend.apps.silver.devops.gov.bc.ca)

fix(GHA): remove database from image retags

---

backend/src/v1/services/file-upload-service.ts

Fixes a bug in which CSV files slightly below the expected size threshold were not being allowed.  It was a matter of recognizing that there are two different definitions of a megabyte.  See the Jira ticket for an explanation of the problem.
Fixes # [GEO-340](https://finrms.atlassian.net/browse/GEO-340)
Manual test against two different CSV files: one 7.999 MB (on disk) and one 8.001MB (on disk).  The smaller is now allowed, and the larger is disallowed.
---
- [Frontend](https://pay-transparency-pr-251-frontend.apps.silver.devops.gov.bc.ca)

backend now enforces max file size based on disk size not network transfer size

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/cd-to-prod-on-workflow-dispatch.yml
backend/src/v1/routes/auth-routes.ts
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-253-frontend.apps.silver.devops.gov.bc.ca)

fix: pvc sizes for main instance and backup

---

.github/workflows/cd-to-dev-on-merge-to-main.yml

---
- [Frontend](https://pay-transparency-pr-255-frontend.apps.silver.devops.gov.bc.ca)

fix: merge to main, queue multiple workflows

---

frontend/src/components/Login.vue

https://finrms.atlassian.net/browse/GEO-337
Updated word from 'portal' to 'tool' on Login.vue
---
- [Frontend](https://pay-transparency-pr-256-frontend.apps.silver.devops.gov.bc.ca)

change-word-on-the-landing-page

---

frontend/src/components/Footer.vue
frontend/src/components/InputForm.vue

Changed i.e. to Ex. and change the capitalization of Employer to a lower case e.
https://finrms.atlassian.net/browse/GEO-169
---
- [Frontend](https://pay-transparency-pr-266-frontend.apps.silver.devops.gov.bc.ca)

feat: verbiage-for-input-screen-GEO-169

---

frontend/src/components/InputForm.vue

Input form data restriction - textarea maxlength and counter 
https://finrms.atlassian.net/browse/GEO-341
---
- [Frontend](https://pay-transparency-pr-268-frontend.apps.silver.devops.gov.bc.ca)

feat: 'Input form textarea maxlength and counter'

---

frontend/src/components/DraftReportPage.vue

Changed button label to 'Generate Final Report'. 
https://finrms.atlassian.net/browse/GEO-384
---
- [Frontend](https://pay-transparency-pr-271-frontend.apps.silver.devops.gov.bc.ca)

feat: changed button label to 'Generate Final Report'

---

.github/workflows/.deploy.yml

---
- [Frontend](https://pay-transparency-pr-276-frontend.apps.silver.devops.gov.bc.ca)

refactor(ci): refactor the code to make it more steps in the action

---

frontend/src/components/Login.vue

https://finrms.atlassian.net/browse/GEO-389
---
- [Frontend](https://pay-transparency-pr-280-frontend.apps.silver.devops.gov.bc.ca)

fix(frontend): style of landing page stepper

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml

---
- [Frontend](https://pay-transparency-pr-284-frontend.apps.silver.devops.gov.bc.ca)

fix(GHA): image tag of backend-external

---

frontend/src/components/InputForm.vue

Minor text update changing e.g. to 'for example' and 'that is'.
https://finrms.atlassian.net/browse/GEO-169

feat: verbiage-for-input-screen/screen-1-GEO-169

---

frontend/src/components/InputForm.vue

Recent changes to InputForm.vue introduced several typescript warnings.  This patch adds explicit types to some variables to fix those warnings.  No functionally has changed.
Existing unit tests pass.  Visual inspection of InputForm and manually tested its behaviour.
---
- [Frontend](https://pay-transparency-pr-294-frontend.apps.silver.devops.gov.bc.ca)

fix: fixed typescript warnings

---

frontend/src/components/InputForm.vue

https://finrms.atlassian.net/browse/GEO-169
Uncapitalized 'Limitations' in descriptive text.
---
- [Frontend](https://pay-transparency-pr-295-frontend.apps.silver.devops.gov.bc.ca)

feat(frontend): verbiage for input screen/screen 1 geo 169

---

frontend/src/components/InputForm.vue
frontend/src/store/modules/config.ts

Fix display maximum file upload size
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-399))
---
- [Frontend](https://pay-transparency-pr-296-frontend.apps.silver.devops.gov.bc.ca)

fix: display max file upload size

---

frontend/src/components/Footer.vue

adding native land acknowledgment message
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-414))
---
- [Frontend](https://pay-transparency-pr-297-frontend.apps.silver.devops.gov.bc.ca)

feat: adding native land acknowledgement message

---

frontend/src/components/Dashboard.vue

Fixes # [GEO-328](https://finrms.atlassian.net/browse/GEO-328)
Visual inspection of dashboard screen
---
- [Frontend](https://pay-transparency-pr-303-frontend.apps.silver.devops.gov.bc.ca)

Dashboard verbiage change, and added new 'submission date' column to list of reports.

---

.github/workflows/.deploy.yml
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/charts/crunchy-postgres/templates/_helpers.tpl
charts/fin-pay-transparency/charts/crunchy-postgres/templates/secret.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-309-frontend.apps.silver.devops.gov.bc.ca)

feat: crunchy s3 backup configuration added.

---

frontend/src/components/Footer.vue

Fix footer overlaps on Confirmation Dialog
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-427))
---
- [Frontend](https://pay-transparency-pr-316-frontend.apps.silver.devops.gov.bc.ca)

Fix Footer overlaps on Confirmation Dialog

---

backend-external/package-lock.json
backend-external/package.json
backend-external/src/app.spec.ts
backend-external/src/app.ts
backend-external/src/config/index.ts
backend-external/src/logger.ts
backend-external/src/utils.ts
backend-external/src/v1/routes/pay-transparency-routes.spec.ts
backend-external/src/v1/routes/pay-transparency-routes.ts
backend-external/src/v1/services/pay-transparency-service.spec.ts
backend/package-lock.json
backend/package.json
backend/src/external-consumer-app.spec.ts
backend/src/external-consumer-app.ts
backend/src/v1/routes/external-consumer-routes.spec.ts
backend/src/v1/routes/external-consumer-routes.ts
backend/src/v1/services/external-consumer-service.spec.ts
backend/src/v1/services/external-consumer-service.ts
charts/fin-pay-transparency/charts/backend-external/templates/deployment.yaml
charts/fin-pay-transparency/charts/backend-external/templates/route.yaml

The data has to be sent de-normalized and should include the Report, Company, Naics Code, Employee Range, Calculated and Suppressed Data.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-422))
---
- [Frontend](https://pay-transparency-pr-315-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-315-frontend.apps.silver.devops.gov.bc.ca)

feat: geo 46 create api to provide freida with suppressed data and calculated table data

---

backend-external/src/v1/routes/pay-transparency-routes.ts

Remove swagger ui default params
---
- [Frontend](https://pay-transparency-pr-318-frontend.apps.silver.devops.gov.bc.ca)

feat: remove swagger ui default params

---

doc-gen-service/src/templates/report-template-header.html

Fixes # [GEO-385](https://finrms.atlassian.net/browse/GEO-385)
Visual inspection of report
---
- [Frontend](https://pay-transparency-pr-320-frontend.apps.silver.devops.gov.bc.ca)

feat: made the draft watermark darker and the font size larger

---

backend/db/migrations/V1.0.18__adding_tables_indexing.sql
backend/src/v1/prisma/schema.prisma

add indexes to improve database queries
The application should function like before. And the external api should working too.
---
- [Frontend](https://pay-transparency-pr-326-frontend.apps.silver.devops.gov.bc.ca)

feat(database): add indexes to improve database queries

---

.github/workflows/.deploy.yml
.github/workflows/.e2e.yml
.github/workflows/analysis.yml
.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/ci_cd_on_pr_dev_sandbox.yml

---
- [Frontend](https://pay-transparency-pr-327-frontend.apps.silver.devops.gov.bc.ca)

chore(GHA): renaming workflows and adding codeql to PR.

---

backend/src/v1/services/auth-service.spec.ts
backend/src/v1/services/auth-service.ts
frontend/src/components/ContactError.vue
frontend/src/router.js

https://finrms.atlassian.net/browse/GEO-335
---
- [Frontend](https://pay-transparency-pr-335-frontend.apps.silver.devops.gov.bc.ca)

feat: Detect missing bceid data

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-332-frontend.apps.silver.devops.gov.bc.ca)

chore: separate values file per environment and remove crunchy pvc backup

---

.github/workflows/cd-to-dev-on-merge-to-main.yml
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml

---
- [Frontend](https://pay-transparency-pr-337-frontend.apps.silver.devops.gov.bc.ca)

feat(database)!: crunchy DR

---

charts/fin-pay-transparency/values-pr.yaml

---
- [Frontend](https://pay-transparency-pr-340-frontend.apps.silver.devops.gov.bc.ca)

chore: increasing PR DB PVC size

---

frontend/src/components/InputForm.vue

Remove extra verbiage from the confirm message.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-421))
---
- [Frontend](https://pay-transparency-pr-342-frontend.apps.silver.devops.gov.bc.ca)

fix: remove extra confirm dialog text

---

backend-external/src/v1/routes/pay-transparency-routes.ts

add get reports endpoint description
---
- [Frontend](https://pay-transparency-pr-346-frontend.apps.silver.devops.gov.bc.ca)

feat: add get reports endpoint description

---

frontend/e2e/auth.setup.ts
frontend/e2e/auth.teardown.ts
frontend/e2e/pages/dashboard.ts
frontend/e2e/pages/generate-report.ts
frontend/e2e/pages/login.ts
frontend/e2e/pages/page.ts
frontend/e2e/reports.spec.ts
frontend/e2e/utils/index.ts
frontend/playwright.config.ts

Adding login and logout end-to-end tests
---
- [Frontend](https://pay-transparency-pr-334-frontend.apps.silver.devops.gov.bc.ca)

feat(e2e): Adding login and logout end to end tests

---

frontend/src/components/InputForm.vue

Static text update for the tooltips. 
https://finrms.atlassian.net/browse/GEO-467
---
- [Frontend](https://pay-transparency-pr-352-frontend.apps.silver.devops.gov.bc.ca)

updated static text for tooltips

---

frontend/index.html
frontend/public/snowplow.js

---
- [Frontend](https://pay-transparency-pr-353-frontend.apps.silver.devops.gov.bc.ca)

feat: adding snowplow.js

---

.vscode/launch.json
frontend/src/components/InputForm.vue

---
- [Frontend](https://pay-transparency-pr-355-frontend.apps.silver.devops.gov.bc.ca)

feat: New error messages design

---

frontend/Caddyfile

---
- [Frontend](https://pay-transparency-pr-357-frontend.apps.silver.devops.gov.bc.ca)

fix: adding snowplow to Caddyfile

---

.github/workflows/merge-to-main.yml

---
- [Frontend](https://pay-transparency-pr-359-frontend.apps.silver.devops.gov.bc.ca)

fix(GHA): merge to main , fix tagging of test and order of zap scan for test deployment

---

.github/workflows/merge-to-main.yml

Refs: PR#358, PR#359
---
- [Frontend](https://pay-transparency-pr-360-frontend.apps.silver.devops.gov.bc.ca)

revert: Revert 358,359 auto deploy to test

---

frontend/src/common/csvService.ts

https://finrms.atlassian.net/browse/GEO-374
---
- [Frontend](https://pay-transparency-pr-364-frontend.apps.silver.devops.gov.bc.ca)

fix: text change for file-too-large error

---

frontend/src/App.vue
frontend/src/components/util/SnackBar.vue

Updated the styling of snackbar notifications to match accessibility standards.  Colors for 'success', 'info', 'warning' and 'error' notifications were all updated (the change also affects the colors of regular alerts.)
Fixes # [GEO-386](https://finrms.atlassian.net/browse/GEO-386)
Visual inspection within the application
---
- [Frontend](https://pay-transparency-pr-378-frontend.apps.silver.devops.gov.bc.ca)

fix: updated snackbar styling

---

backend/src/v1/services/report-service.ts

Order report in descending order by reporting year
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-502))
---
- [Frontend](https://pay-transparency-pr-379-frontend.apps.silver.devops.gov.bc.ca)

fix - order report in descending order by reporting year

---

.github/workflows/analysis.yml
.gitignore

Exclude doc-gen-service templates from code cov
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-445))
---
- [Frontend](https://pay-transparency-pr-380-frontend.apps.silver.devops.gov.bc.ca)

feat - exclude doc-gen-service templates from code cov

---

frontend/src/components/NotFound.vue

fix return to dashboard from 404 page
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-509))
---
- [Frontend](https://pay-transparency-pr-381-frontend.apps.silver.devops.gov.bc.ca)

fix: return to dashboard from 404 page

---

frontend/src/components/Footer.vue

Fix footer font size and yellow line in the bottom is missing as compared to gov.bc.ca and the hyperlinks are not underlined
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-513))
---
- [Frontend](https://pay-transparency-pr-391-frontend.apps.silver.devops.gov.bc.ca)

fix:  geo 513 fix footer styles

---

frontend/src/components/Login.vue

allow landing page how to use the tool steps to be tabbable
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-518))
---
- [Frontend](https://pay-transparency-pr-393-frontend.apps.silver.devops.gov.bc.ca)

fix: allow landing page how to use the tool steps to be tabbable

---

frontend/e2e/pages/dashboard.ts
frontend/src/components/Dashboard.vue

Move generate report button caption to the correct position
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-168))
---
- [Frontend](https://pay-transparency-pr-394-frontend.apps.silver.devops.gov.bc.ca)

fix: move generate report button caption to correct position

---

frontend/src/components/Header.vue
maintenance/src/assets/css/styles.css
maintenance/src/index.html

Accessibility: User Option (right corner) Labelling
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-511))
---
- [Frontend](https://pay-transparency-pr-396-frontend.apps.silver.devops.gov.bc.ca)

fix: Accessibility: User Option (right corner) Labelling

---

.github/workflows/cd-to-test-on-workflow-dispatch.yml

---
- [Frontend](https://pay-transparency-pr-397-frontend.apps.silver.devops.gov.bc.ca)

feat: added environment

---

frontend/src/components/Footer.vue

update footer to fix typo
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-523))
---
- [Frontend](https://pay-transparency-pr-399-frontend.apps.silver.devops.gov.bc.ca)

fix: update footer to fix typo

---

frontend/src/components/InputForm.vue

https://finrms.atlassian.net/browse/GEO-522
---
- [Frontend](https://pay-transparency-pr-403-frontend.apps.silver.devops.gov.bc.ca)

feat: Add label to remove file icon

---

doc-gen-service/src/templates/report-template-emp-data-summary.html
frontend/src/components/DraftReportPage.vue
frontend/src/components/PublishedReportPage.vue
frontend/src/components/util/HtmlReport.vue

- Gave the HTML report a minimum width (instead of using a responsive width).  This avoids layout problems that arise on small screens.  On small screens, horizontal scrolling is now required to view the full width of the report (in addition to vertical scrolling to view the full height of the report).
- Minor edits to text in report sub-headings.  
Fixes # [GEO-524](https://finrms.atlassian.net/browse/GEO-524)
Visual inspection of HTML and PDF reports (for HTML reports, reviewed in different size browser windows)
---
- [Frontend](https://pay-transparency-pr-409-frontend.apps.silver.devops.gov.bc.ca)
---
- …

feat: report adjustments

---

frontend/src/components/Login.vue

Remove a debugging statement that was accidently left in the code.
Manual test in a browser
---
- [Frontend](https://pay-transparency-pr-410-frontend.apps.silver.devops.gov.bc.ca)

fix: remove debugging statement

---

frontend/src/components/Header.vue
frontend/src/components/InputForm.vue

Accessibility: User Option (right corner) Labelling
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-511))
---
- [Frontend](https://pay-transparency-pr-414-frontend.apps.silver.devops.gov.bc.ca)

fix: allow narration of user profile information

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-420-frontend.apps.silver.devops.gov.bc.ca)

chore: DRE

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-421-frontend.apps.silver.devops.gov.bc.ca)

chore: revert DRE

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-422-frontend.apps.silver.devops.gov.bc.ca)

chore: update dre

---

maintenance/src/index.html

---
- [Frontend](https://pay-transparency-pr-427-frontend.apps.silver.devops.gov.bc.ca)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/merge.yml …

fix: Geo 520 maintenance page formatting is not displaying when user is logged in and application is killed

---

frontend/package-lock.json
frontend/package.json

---
- [Frontend](https://pay-transparency-pr-429-frontend.apps.silver.devops.gov.bc.ca)

chore: upgrade playwright to latest version

---

doc-gen-service/package-lock.json
doc-gen-service/package.json
doc-gen-service/src/server.spec.ts
doc-gen-service/src/server.ts
doc-gen-service/src/v1/services/puppeteer-service.ts
frontend/src/components/Header.vue

https://finrms.atlassian.net/browse/GEO-501
---
- [Frontend](https://pay-transparency-pr-433-frontend.apps.silver.devops.gov.bc.ca)

fix: sonar issues

---

backend-external/tests/integration/integration.spec.ts

---
- [Frontend](https://pay-transparency-pr-438-frontend.apps.silver.devops.gov.bc.ca)

fix: integration timeout

---

backend-external/src/v1/routes/pay-transparency-routes.ts
backend/src/v1/routes/external-consumer-routes.spec.ts
backend/src/v1/routes/external-consumer-routes.ts
backend/src/v1/services/external-consumer-service.spec.ts
backend/src/v1/services/external-consumer-service.ts

Update Backend-external api output
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-557))
---
- [Frontend](https://pay-transparency-pr-439-frontend.apps.silver.devops.gov.bc.ca)

feat: changing the shape of the output of the external api

---

backend-external/src/v1/routes/pay-transparency-routes.ts
backend/src/v1/routes/external-consumer-routes.spec.ts
backend/src/v1/routes/external-consumer-routes.ts
backend/src/v1/services/external-consumer-service.spec.ts
backend/src/v1/services/external-consumer-service.ts

fix: pageSize and page, fix date filter, remove records count
---
- [Frontend](https://pay-transparency-pr-441-frontend.apps.silver.devops.gov.bc.ca)

fix: pageSize and page, fix date filter, remove records count

---

backend-external/tests/integration/integration.spec.ts

---
- [Frontend](https://pay-transparency-pr-442-frontend.apps.silver.devops.gov.bc.ca)

feat: fix integration test assertion

---

backend/src/config/index.ts
backend/src/v1/prisma/prisma-client-readonly-replica.ts
charts/fin-pay-transparency/templates/configmap.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-443-frontend.apps.silver.devops.gov.bc.ca)

chore: move connection pool size to configuration

---

.github/workflows/analysis.yml
.github/workflows/codeql.yml

---
- [Frontend](https://pay-transparency-pr-444-frontend.apps.silver.devops.gov.bc.ca)

fix(ci): codeql collision

---

frontend/package-lock.json
frontend/package.json

---
- [Frontend](https://pay-transparency-pr-445-frontend.apps.silver.devops.gov.bc.ca)

fix(frontend): axios security issue

---

.github/workflows/merge.yml
frontend/package-lock.json
frontend/package.json

Upgrade playwright to allow run on local environment app
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-526))
---
- [Frontend](https://pay-transparency-pr-449-frontend.apps.silver.devops.gov.bc.ca)

fix: Upgrade playwright to allow run on local environment app

---

charts/fin-pay-transparency/charts/backend-external/templates/deployment.yaml
charts/fin-pay-transparency/charts/backend/templates/deployment.yaml
charts/fin-pay-transparency/charts/doc-gen-service/templates/deployment.yaml
charts/fin-pay-transparency/charts/frontend/templates/deployment.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-453-frontend.apps.silver.devops.gov.bc.ca)

chore(CD): HELM changes to roll deployments every time

---

.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml
.github/workflows/merge.yml
.github/workflows/scheduled.yml

---
- [Frontend](https://pay-transparency-pr-454-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): removed ZAP from DEV, TEST and Added to PROD

---

frontend/src/components/Login.vue

Use dashboard layout margins in the landing page
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-583))
---
- [Frontend](https://pay-transparency-pr-456-frontend.apps.silver.devops.gov.bc.ca)

fix: use dashboard layout margins in landing page

---

backend/package.json
backend/src/v1/routes/auth-routes.spec.ts
backend/src/v1/routes/auth-routes.ts
backend/src/v1/services/auth-service.spec.ts
backend/src/v1/services/auth-service.ts

https://finrms.atlassian.net/browse/GEO-562
---
- [Frontend](https://pay-transparency-pr-457-frontend.apps.silver.devops.gov.bc.ca)

fix(backend): Ensure user is logged out if error during login

---

frontend/src/components/Footer.vue

margins on footer - https://finrms.atlassian.net/browse/GEO-590
sonar issues - https://finrms.atlassian.net/browse/GEO-501
---
- [Frontend](https://pay-transparency-pr-461-frontend.apps.silver.devops.gov.bc.ca)

fix: sonar issues and margins

---

frontend/src/components/Login.vue

Removed the words “on all your B.C. employees” from the first sentence on the landing page.
Fixes # [GEO-609](https://finrms.atlassian.net/browse/GEO-609)
Visual inspection of the landing page.
[GEO-609]: https://finrms.atlassian.net/browse/GEO-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-479-frontend.apps.silver.devops.gov.bc.ca)

feat: updated text on the landing page

---

backend/src/v1/routes/external-consumer-routes.spec.ts
backend/src/v1/services/external-consumer-service.spec.ts
backend/src/v1/services/external-consumer-service.ts

Using a custom query to fetch reports
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-599))
---
- [Frontend](https://pay-transparency-pr-473-frontend.apps.silver.devops.gov.bc.ca)

fix: use custom query to get reports

---

backend/src/v1/services/external-consumer-service.ts

Return the correct page number from external API response
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-599))
---
- [Frontend](https://pay-transparency-pr-483-frontend.apps.silver.devops.gov.bc.ca)

fix: return correct page number from external api response

---

charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml

---
- [Frontend](https://pay-transparency-pr-485-frontend.apps.silver.devops.gov.bc.ca)

fix(backend): session pvc size

---

.jira/config.yml

---
- [Frontend](https://pay-transparency-pr-490-frontend.apps.silver.devops.gov.bc.ca)

chore: adding git env to jira mapping GEO-628

---

frontend/src/components/Login.vue

Updated two different links on the landing page to refer to new BC Gov URLs.
Fixes # [GEO-618](https://finrms.atlassian.net/browse/GEO-618)
Visual inspection of the application
[GEO-618]: https://finrms.atlassian.net/browse/GEO-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-492-frontend.apps.silver.devops.gov.bc.ca)

feat: updated links on the landing page

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-497-frontend.apps.silver.devops.gov.bc.ca)

chore: updating memoery allocation

---

backend/src/v1/services/report-service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/Dashboard.vue
frontend/src/components/__tests__/Dashboard.spec.ts
frontend/src/components/util/ReportsTable.vue
frontend/src/components/util/__tests__/ReportsTable.spec.ts

Add pagination using v-datatable
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-546))
---
- [Frontend](https://pay-transparency-pr-504-frontend.apps.silver.devops.gov.bc.ca)

feat: geo 546 convert dashboard vtable into v datatable add pagination and other table features

---

backend/src/v1/services/report-service.ts

---
- [Frontend](https://pay-transparency-pr-509-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-509-admin-frontend.apps.silver.devops.gov.bc.ca)

fix: reverted a change that shouldn't have been committed

---

admin-frontend/package.json
admin-frontend/vite.config.js
backend/src/config/index.ts
charts/fin-pay-transparency/charts/admin-frontend/templates/deployment.yaml
charts/fin-pay-transparency/charts/backend/templates/deployment.yaml

---
- [Frontend](https://pay-transparency-pr-508-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-508-admin-frontend.apps.silver.devops.gov.bc.ca)

feat: changed the backend's admin api port to 3004

---

backend/src/admin-app.ts

---
- [Frontend](https://pay-transparency-pr-519-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-519-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-519-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix(backend): make sure distinct strategy names are used for admin and public site.

---

backend/src/v1/services/report-service.ts

https://finrms.atlassian.net/browse/GEO-708
---
- [Frontend](https://pay-transparency-pr-526-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-526-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-526-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix(backend): save user_id when report is updated

---

.github/workflows/.e2e-admin.yml
admin-frontend/src/App.vue
admin-frontend/src/__tests__/App.spec.ts
admin-frontend/src/components/SideBar.vue
admin-frontend/src/components/__tests__/SideBar.spec.ts

UI changes to the Admin frontend:
- Made the menu side bar collapsible.  
- Added a back button that appears at the top-left of each "page"
New unit test
---
- [Frontend](https://pay-transparency-pr-525-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-525-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-525-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

feat: admin collapsible sidebar and back button

---

backend-external/src/v1/routes/pay-transparency-routes.spec.ts
backend-external/src/v1/routes/pay-transparency-routes.ts
backend/src/v1/services/external-consumer-service.spec.ts

Add maximum page size validation  before it is forwarded to the backend API
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-731))
---
- [Frontend](https://pay-transparency-pr-533-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-533-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-533-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/ …

fix: add max page size validation 

---

backend/src/v1/services/report-service.spec.ts
backend/src/v1/services/report-service.ts

https://finrms.atlassian.net/browse/GEO-732
---
- [Frontend](https://pay-transparency-pr-535-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-535-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-535-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix(backend): First published report's revision should be 1

---

charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

https://finrms.atlassian.net/browse/GEO-736
---
- [Frontend](https://pay-transparency-pr-536-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-536-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-536-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
---
- …

chore(crunchy): changes for crunchy-postgres to have local pvc backup in openshift

---

admin-frontend/src/components/ReportsPage.vue
admin-frontend/src/components/__tests__/ReportsPage.spec.ts
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/__tests__/reportSearchStore.spec.ts
admin-frontend/src/store/modules/reportSearchStore.ts
backend/package-lock.json
backend/package.json
backend/src/v1/routes/admin-report-routes.spec.ts
backend/src/v1/routes/admin-report-routes.ts
backend/src/v1/services/admin-report-service.spec.ts
backend/src/v1/services/admin-report-service.ts

- Updated admin backend endpoint for GET /admin-api/v1/reports to support CSV output (in addition to JSON, which was already supported).  Pagination is required for JSON, but not for CSV.
- Updated the admin frontend to connect the "Export results" button to the new backend.
Fixes # [GEO-630](https://finrms.atlassian.net/browse/GEO-630)
New unit tests.  Updated some existing unit tests.
[GEO-630]: https://finrms.atlassian.net/browse/GEO-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-554-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-554-admin-frontend.apps.silver.devops.gov.bc.ca)
- …

feat: admin export reports csv

---

backend/db/migrations/V1.0.27__admin_tables.sql
backend/src/config/index.ts
backend/src/v1/prisma/schema.prisma
backend/src/v1/routes/admin-auth-routes.spec.ts
backend/src/v1/routes/admin-auth-routes.ts
backend/src/v1/routes/admin-users-routes.spec.ts
backend/src/v1/routes/admin-users-routes.ts
backend/src/v1/services/admin-auth-service.spec.ts
backend/src/v1/services/admin-auth-service.ts
backend/src/v1/services/admin-report-service.spec.ts
backend/src/v1/services/admin-users-service.spec.ts
backend/src/v1/services/admin-users-services.ts
backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts
backend/src/v1/validations/index.ts
backend/src/v1/validations/schemas.ts

This PR addresses the ticket [GEO-660](https://finrms.atlassian.net/browse/GEO-660)
---
- [Frontend](https://pay-transparency-pr-555-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-555-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-555-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
---
Deployments, as …

feat: GEO-868 Add users admin api

---

admin-frontend/src/components/UserManagementPage.vue
admin-frontend/src/components/__tests__/UserManagementPage.spec.ts
admin-frontend/src/types/index.ts
backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts

Merge user from the PTRT ADMIN and USER role from keycloak
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-927))
---
- [Frontend](https://pay-transparency-pr-561-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-561-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-561-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: merging users from admin and user role

---

admin-frontend/package-lock.json
admin-frontend/package.json
admin-frontend/src/App.vue
admin-frontend/src/__tests__/App.spec.ts
admin-frontend/src/components/ReportSearchFilters.vue
admin-frontend/src/components/UserManagementPage.vue
admin-frontend/src/components/user-management/AddUserButton.vue
admin-frontend/src/components/user-management/__tests__/AddUserButton.spec.ts
admin-frontend/src/components/util/SnackBar.vue
admin-frontend/src/constants/index.ts
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/__tests__/usersStore.spec.ts
admin-frontend/src/store/modules/usersStore.ts
admin-frontend/src/types/index.ts
backend/src/v1/routes/admin-users-routes.spec.ts
backend/src/v1/routes/admin-users-routes.ts
backend/src/v1/services/admin-users-service.spec.ts
backend/src/v1/services/admin-users-services.ts
backend/src/v1/validations/schemas.ts

Add dialog to add user in the frontend
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-660))
---
- [Frontend](https://pay-transparency-pr-564-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-564-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-564-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: add user dialog frontend changes

---

backend/db/migrations/V1.0.28__comments.sql

https://finrms.atlassian.net/browse/GEO-617
---
- [Frontend](https://pay-transparency-pr-565-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-565-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-565-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-617 Add comments to database

---

admin-frontend/package-lock.json
admin-frontend/package.json
admin-frontend/src/__tests__/App.spec.ts
admin-frontend/src/components/UserCard.vue
admin-frontend/src/components/UserManagementPage.vue
admin-frontend/src/components/user-management/AddUserButton.vue
admin-frontend/src/components/user-management/UserCard.vue
admin-frontend/src/components/user-management/__tests__/AddUserButton.spec.ts
admin-frontend/src/components/user-management/__tests__/UserCard.spec.ts
admin-frontend/src/constants/index.ts
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/__tests__/usersStore.spec.ts
admin-frontend/src/store/modules/reportSearchStore.ts
admin-frontend/src/store/modules/usersStore.ts
admin-frontend/src/types/index.ts
backend/db/migrations/V1.0.28__add_username_to_admin_users.sql
backend/db/migrations/V1.0.29__add_username_to_admin_users.sql
backend/src/constants/admin.ts
backend/src/v1/prisma/schema.prisma
backend/src/v1/routes/admin-users-routes.spec.ts
backend/src/v1/routes/admin-users-routes.ts
backend/src/v1/services/admin-auth-service.spec.ts
backend/src/v1/services/admin-auth-service.ts
backend/src/v1/services/admin-users-services.ts
backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts
backend/src/v1/types/users.ts
backend/src/v1/validations/index.ts
backend/src/v1/validations/schemas.ts

Implementing user management functionality to update user roles, and delete/deactivate users
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-733))
---
- [Frontend](https://pay-transparency-pr-566-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-566-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-566-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

feat: user management assign role and delete user

---

admin-frontend/src/App.vue
admin-frontend/src/__tests__/App.spec.ts
admin-frontend/src/components/InvitationExpired.vue
admin-frontend/src/components/Login.vue
admin-frontend/src/components/LoginError.vue
admin-frontend/src/components/ReportsPage.vue
admin-frontend/src/components/TokenExpired.vue
admin-frontend/src/components/util/AuthLayout.vue
admin-frontend/src/router.js
admin-frontend/src/utils/constant.js

1. Created a reusable component for auth pages
2. Added invitation expired page with placeholder verbiage
3. Fixed admin App.spec.ts flaky test
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-911))
---
- [Frontend](https://pay-transparency-pr-573-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-573-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-573-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After …

feat: geo 911 UI page for onboarding expired

---

backend/src/v1/email-templates/index.ts
backend/src/v1/services/admin-users-service.spec.ts
backend/src/v1/services/admin-users-services.ts

Updating user invite email template
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-910))
---
- [Frontend](https://pay-transparency-pr-576-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-576-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-576-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: adding email template

---

backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts

get id of admin user from our local database for use in frontend
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-970))
---
- [Frontend](https://pay-transparency-pr-577-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-577-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-577-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …

fix: get id of admin user from our local database for use in frontend

---

.github/workflows/analysis.yml
frontend/src/components/Login.vue

https://finrms.atlassian.net/browse/GEO-958
there were some major prettier changes to the login.vue page. so I split my changes and the prittier changes into seperate commits so it's easier to see what I've changed.
---
- [Frontend](https://pay-transparency-pr-578-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-578-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-578-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- …

fix: GEO-958 Fix issues reported by sonar

---

admin-frontend/src/components/UserManagementPage.vue
admin-frontend/src/components/user-management/PendingAccess.vue
admin-frontend/src/components/user-management/__tests__/PendingAccess.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/__tests__/userInvitesStore.spec.ts
admin-frontend/src/types/index.ts

Adding user management pending access UI
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-963))
---
- [Frontend](https://pay-transparency-pr-586-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-586-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-586-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: geo 963 user management pending access UI

---

admin-frontend/src/components/InvitationExpired.vue

Update expired onboarding page verbiage
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-911))
---
- [Frontend](https://pay-transparency-pr-587-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-587-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-587-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: update expired onboarding page verbiage

---

sysdig/sysdig.yml

---
- [Frontend](https://pay-transparency-pr-589-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-589-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-589-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: geo-221 added team members to sysdig

---

admin-frontend/src/components/UnauthorizedError.vue
admin-frontend/src/router.js
admin-frontend/src/utils/constant.js
backend/src/v1/routes/admin-auth-routes.ts

https://finrms.atlassian.net/browse/GEO-577
---
- [Frontend](https://pay-transparency-pr-597-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-597-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-597-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: Unauthorized page when logging in with no roles

---

charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

Set invitation link active duration to 72 hours
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-979))
---
- [Frontend](https://pay-transparency-pr-600-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-600-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-600-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: set invitation link active duration to 72 hours

---

admin-frontend/src/components/__tests__/UserManagementPage.spec.ts
admin-frontend/src/components/user-management/UserCard.vue
admin-frontend/src/components/user-management/__tests__/PendingAccess.spec.ts
admin-frontend/src/components/user-management/__tests__/UserCard.spec.ts
backend/src/v1/services/admin-auth-service.spec.ts
backend/src/v1/services/admin-auth-service.ts

Prevent users from deleting or modifying their own permissions
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-991))
---
- [Frontend](https://pay-transparency-pr-601-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-601-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-601-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: prevent users from deleting or modifying their own permissions

---

admin-frontend/src/components/user-management/PendingAccess.vue
admin-frontend/src/store/modules/__tests__/userInvitesStore.spec.ts
admin-frontend/src/store/modules/userInvitesStore.ts
admin-frontend/src/store/modules/usersStore.ts

https://finrms.atlassian.net/browse/GEO-981
---
- [Frontend](https://pay-transparency-pr-603-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-603-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-603-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-981 Sort admin user list and pending list. Hide pagination unless needed.

---

charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-606-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-606-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-606-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: updated pvc size for dev and test

---

.vscode/tasks.json
backend/package-lock.json
backend/package.json
backend/src/v1/services/admin-auth-service.ts
backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts

https://finrms.atlassian.net/browse/GEO-992
---
- [Frontend](https://pay-transparency-pr-607-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-607-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-607-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-992 Update db when sso and db are mismatched

---

backend/db/sample-data/generate_random_reports_companies_users.sql

https://finrms.atlassian.net/browse/GEO-996
---
- [Frontend](https://pay-transparency-pr-609-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-609-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-609-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-996 Sample db data

---

backend/db/migrations/V1.0.34__announcement_resource_history_link_announcement_history.sql
backend/src/v1/middlewares/authorization/authenticate-admin.spec.ts
backend/src/v1/middlewares/authorization/authenticate-admin.ts
backend/src/v1/prisma/schema.prisma
backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/routes/announcement-routes.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/types/announcements.ts
backend/src/v1/types/index.ts

adding delete announcements API
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-887))
---
- [Frontend](https://pay-transparency-pr-610-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-610-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-610-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: adding delete announcements api

---

admin-frontend/src/components/ReportSearchFilters.vue

https://finrms.atlassian.net/browse/GEO-1006
---
- [Frontend](https://pay-transparency-pr-613-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-613-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-613-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1006 Close datepicker automatically when selecting range

---

admin-frontend/src/components/Header.vue
admin-frontend/src/components/ReportsPage.vue
admin-frontend/src/components/SideBar.vue

https://finrms.atlassian.net/browse/GEO-995
---
- [Frontend](https://pay-transparency-pr-614-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-614-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-614-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-995 Added labels to unnamed buttons

---

renovate.json

---
- [Frontend](https://pay-transparency-pr-615-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-615-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-615-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-1019 renovate fix for vue

---

renovate.json

---
- [Frontend](https://pay-transparency-pr-616-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-616-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-616-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix(deps): renovate config GEO 1031

---

admin-frontend/src/components/AnnouncementsPage.vue

A simple PR to unblock work on the "Add announcements" page.  This covers a small part of the requirements for https://finrms.atlassian.net/browse/GEO-937.
---
- [Frontend](https://pay-transparency-pr-618-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-618-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-618-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

feat: Admin - added an 'Add announcement' button

---

backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/types/announcements.ts

Add title to announcement filter 
---
- [Frontend](https://pay-transparency-pr-624-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-624-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-624-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

fix: geo 861 add title to filter

---

.github/workflows/.deploy.yml
backend/src/config/index.ts
backend/src/v1/email-templates/index.ts
charts/fin-pay-transparency/templates/secret.yaml

https://finrms.atlassian.net/browse/GEO-1021
---
- [Frontend](https://pay-transparency-pr-623-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-623-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-623-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: Use Admin Portal vanity URL in email

---

backend/src/v1/routes/admin-users-routes.spec.ts
backend/src/v1/routes/admin-users-routes.ts
backend/src/v1/services/admin-auth-service.ts
backend/src/v1/services/sso-service.spec.ts
backend/src/v1/services/sso-service.ts

https://finrms.atlassian.net/browse/GEO-1024
https://finrms.atlassian.net/browse/GEO-1023
---
- [Frontend](https://pay-transparency-pr-621-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-621-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-621-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
---
Deployments, …

fix: GEO-1023, GEO-1024 Fix update_date and update_user in admin_user table. Fix admin_user_history record. 

---

admin-frontend/src/components/user-management/__tests__/PendingAccess.spec.ts

Fix pending access frontend unit tests
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1027))
---
- [Frontend](https://pay-transparency-pr-625-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-625-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-625-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO 1027  pending access frontend unit tests

---

README.md

https://finrms.atlassian.net/browse/GEO-980
---
- [Frontend](https://pay-transparency-pr-629-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-629-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-629-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-980 Update README.md

---

.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml

---
- [Frontend](https://pay-transparency-pr-630-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-630-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-630-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: admin url GEO-770

---

admin-frontend/src/components/ReportSearchFilters.vue

Add submission date range filter tooltip
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1031))
---
- [Frontend](https://pay-transparency-pr-636-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-636-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-636-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1031 enhance submission date range filter with tooltip

---

admin-frontend/src/components/AnnouncementsPage.vue

Fixes # [GEO-861](https://finrms.atlassian.net/browse/GEO-861)
Visual inspection of the announcements page
---
- [Frontend](https://pay-transparency-pr-637-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-637-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-637-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-861 admin app announcements - updated column headers

---

admin-frontend/src/components/ReportSearchFilters.vue

Add aria label to date cell to address accessibility.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1041))
---
- [Frontend](https://pay-transparency-pr-638-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-638-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-638-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
--- …

fix: GEO 1041 - Add aria label to date cell to address accessibility

---

charts/fin-pay-transparency/values-prod.yaml

---
- [Frontend](https://pay-transparency-pr-643-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-643-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-643-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: update PVC GEO-1044

---

.diagrams/architecture/data-flow-diagrams/pay-transparency-admin-portal-L1.mermaid
.diagrams/architecture/data-flow-diagrams/pay-transparency-context-L0.mermaid
.diagrams/architecture/data-flow-diagrams/pay-transparency-reporting-tool-L1.mermaid

Added auth and backup details to the data flow diagrams.  Changed the naming convention used for processes.
(Use [https://mermaid.live/](https://mermaid.live/) to view the diagrams.  Paste the diagram file contents into the online editor.)
Fixes # [GEO-1043](https://finrms.atlassian.net/browse/GEO-1043)
---
- [Frontend](https://pay-transparency-pr-642-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-642-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-642-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

feat: GEO-1043 updated data flow diagrams

---

admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue

Add publish announcement confirmation
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-863))
---
- [Frontend](https://pay-transparency-pr-645-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-645-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-645-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 863 add publish announcement confirmation

---

admin-frontend/src/App.vue
admin-frontend/src/components/AnnouncementsPage.vue

Fixes # [GEO-861](https://finrms.atlassian.net/browse/GEO-861)
Visual inspection
---
- [Frontend](https://pay-transparency-pr-651-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-651-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-651-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: left align announcement title on announcements page

---

admin-frontend/src/components/EditAnnouncementPage.vue
admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementActions.vue
admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue
admin-frontend/src/router.js
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/__tests__/announcementSelectionStore.spec.ts
admin-frontend/src/store/modules/announcementSelectionStore.ts
admin-frontend/src/types/announcements.ts
admin-frontend/src/utils/constant.js
backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/routes/announcement-routes.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/types/announcements.ts

Announcement page edit feature
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-882))
---
- [Frontend](https://pay-transparency-pr-650-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-650-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-650-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: geo 882 announcement page edit feature

---

admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue

Change publish announncement dialog confirm button
---
- [Frontend](https://pay-transparency-pr-659-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-659-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-659-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: change publish announncement dialog confirm button

---

.github/workflows/.build.yml
.github/workflows/.quota-check.yml
.github/workflows/ci_cd_on_pr_dev_sandbox.yml
.github/workflows/ci_cd_on_pr_hotfix.yml
.github/workflows/cleanup_tag_hotfix-pr-close.yml
README.md
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-hotfix.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-660-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-660-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-660-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: geo 968 hotfix pipeline

---

backend-external/Dockerfile
backend/Dockerfile
charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

1. updated Dockerfile to remove deprecated ENV commands
2. updated crunchy db cpu and mem for PROD (repo host and cronjobs)
3. increase the backup pvc size as per current value in prod
---
- [Frontend](https://pay-transparency-pr-661-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-661-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-661-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

chore: multiple updates GEO-1060

---

admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue

fix error caused by publish and expire date format
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1061))
---
- [Frontend](https://pay-transparency-pr-665-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-665-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-665-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: fix error caused by publish and expire date format

---

clamav-service/src/app.ts

---
- [Frontend](https://pay-transparency-pr-669-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-669-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-669-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: codeql and add path validation

---

clamav-service/src/app.ts

---
- [Frontend](https://pay-transparency-pr-671-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-671-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-671-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: codeql issues

---

admin-frontend/package-lock.json
admin-frontend/package.json
admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/utils/constant.js
clamav-service/src/app.ts

Scanning file before backend upload
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1074))
---
- [Frontend](https://pay-transparency-pr-684-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-684-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-684-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO 1074 scanning file before backend upload

---

admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue

Additional validation for announcements
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1069))
---
- [Frontend](https://pay-transparency-pr-691-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-691-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-691-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1069 additional validation for announcements

---

admin-frontend/src/components/announcements/AnnouncementActions.vue
admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/components/announcements/__tests__/AnnouncementActions.spec.ts
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/routes/announcement-routes.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/services/file-upload-service.spec.ts
backend/src/v1/services/file-upload-service.ts
backend/src/v1/services/utils-service.spec.ts
backend/src/v1/services/utils-service.ts
backend/src/v1/types/announcements.ts

Fixes # [GEO-1067](https://finrms.atlassian.net/browse/GEO-1067)
New unit tests.  Updated existing unit tests
---
- [Frontend](https://pay-transparency-pr-688-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-688-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-688-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/anal …

feat: GEO-1067 admin unpublish announcement

---

admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/utils/constant.js
clamav-service/src/app.ts

Integrate clamav node api in admin frontend 
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1074))
---
- [Frontend](https://pay-transparency-pr-694-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-694-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-694-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1074 integrate clamav node api in admin frontend

---

admin-frontend/src/components/announcements/AnnouncementForm.vue

Correct file upload section title
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1012))
---
- [Frontend](https://pay-transparency-pr-700-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-700-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-700-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: correct file upload section title

---

.github/workflows/ci_cd_on_pr_hotfix.yml
admin-frontend/src/components/DashboardPage.vue

---
- [Frontend](https://pay-transparency-pr-706-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-706-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-706-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

fix: hotfix branch testing

---

.github/workflows/.e2e.yml

https://finrms.atlassian.net/browse/GEO-1076
---
- [Frontend](https://pay-transparency-pr-712-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-712-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-712-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1076 Remove chromium from e2e

---

admin-frontend/package-lock.json
admin-frontend/src/App.vue
admin-frontend/src/components/announcements/AnnouncementForm.vue

https://finrms.atlassian.net/browse/GEO-1100
---
- [Frontend](https://pay-transparency-pr-715-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-715-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-715-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1100 Enable announcement submit button

---

admin-frontend/src/components/announcements/AnnouncementForm.vue

https://finrms.atlassian.net/browse/GEO-1100
---
- [Frontend](https://pay-transparency-pr-720-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-720-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-720-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: Expires-on highlight on error

---

admin-frontend/src/components/DashboardPage.vue
admin-frontend/src/components/ReportsPage.vue
admin-frontend/src/components/TokenExpired.vue

Fixed a few code smells identified by sonar.
Fixes # [GEO-1091](https://finrms.atlassian.net/browse/GEO-1091)
---
- [Frontend](https://pay-transparency-pr-723-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-723-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-723-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
---
Thanks for …

fix: GEO-1091 fix code smells

---

backend/package-lock.json
backend/package.json
renovate.json

fix ms not authenticating
---
- [Frontend](https://pay-transparency-pr-726-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-726-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-726-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: MS Entra not authenticating

---

admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/components/announcements/AnnouncementItem.vue
frontend/src/components/announcements/AnnouncementItem.vue

https://finrms.atlassian.net/browse/GEO-1112
---
- [Frontend](https://pay-transparency-pr-729-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-729-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-729-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1112 Link and attachment icons in announcements

---

admin-frontend/src/components/AddAnnouncementPage.vue
admin-frontend/src/components/EditAnnouncementPage.vue
admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementForm.vue

Update announcement save confirmation messages
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1127))
---
- [Frontend](https://pay-transparency-pr-730-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-730-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-730-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: Update announcement save confirmation messages

---

admin-frontend/src/components/Login.vue

Update Admin Login to Login with IDIR MFA
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1101))
---
- [Frontend](https://pay-transparency-pr-733-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-733-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-733-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/action …

fix: Update Admin Login to Login with IDIR MFA

---

admin-frontend/src/App.vue
admin-frontend/src/components/ReportSearchFilters.vue
admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue
admin-frontend/src/main.js

Make admin app text fields consistent
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1119))
---
- [Frontend](https://pay-transparency-pr-734-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-734-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-734-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1119 admin app consistent look for all form fields

---

backend/src/v1/services/public-auth-service.ts

Identify which attribute is missing from IDIM Soap Response and add it to the log statement.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1118))
---
- [Frontend](https://pay-transparency-pr-740-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-740-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-740-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

fix: include missing company details fields in the logs

---

backend/src/v1/services/announcements-service.ts
backend/src/v1/services/scheduler-service.ts
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

https://finrms.atlassian.net/browse/GEO-888
---
- [Frontend](https://pay-transparency-pr-746-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-746-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-746-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-888 Fix schedules and improve logging

---

admin-frontend/src/components/announcements/AnnouncementActions.vue
admin-frontend/src/components/announcements/AnnouncementForm.vue

Fixes # [GEO-1091](https://finrms.atlassian.net/browse/GEO-1091)
---
- [Frontend](https://pay-transparency-pr-744-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-744-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-744-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-1091 - fixed code smells identified by Sonar

---

.github/workflows/merge.yml

https://finrms.atlassian.net/browse/GEO-1134
---
- [Frontend](https://pay-transparency-pr-747-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-747-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-747-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-1134 Fix admin url

---

backend/src/v1/email-templates/index.ts
backend/src/v1/services/admin-auth-service.ts
backend/src/v1/services/scheduler-service.ts
backend/src/v1/services/sso-service.ts

https://finrms.atlassian.net/browse/GEO-888
---
- [Frontend](https://pay-transparency-pr-748-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-748-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-748-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-888 Fix missing emails and expanded email body

---

admin-frontend/src/App.vue
admin-frontend/src/components/AnnouncementsPage.vue

https://finrms.atlassian.net/browse/GEO-1137
---
- [Frontend](https://pay-transparency-pr-753-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-753-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-753-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1137 adjust contrast for accessibility

---

admin-frontend/src/App.vue
admin-frontend/src/__tests__/App.spec.ts
admin-frontend/src/components/DashboardPage.vue
admin-frontend/src/components/__tests__/DashboardPage.spec.ts
admin-frontend/src/components/dashboard/NumEmployerLogins.vue
admin-frontend/src/components/dashboard/NumSubmissionsThisYear.vue
admin-frontend/src/components/dashboard/PublicAnnouncements.vue
admin-frontend/src/components/dashboard/RecentlySubmittedReports.vue
admin-frontend/src/components/dashboard/RecentlyViewedReports.vue
admin-frontend/src/components/dashboard/ReportsWidget.vue
admin-frontend/src/components/dashboard/__tests__/RecentlySubmittedReports.spec.ts
admin-frontend/src/components/dashboard/__tests__/RecentlyViewedReports.spec.ts
admin-frontend/src/components/reports/ReportActions.vue
admin-frontend/src/types/reports.ts
backend/src/v1/routes/admin-report-routes.ts
backend/src/v1/services/admin-report-service.spec.ts
backend/src/v1/services/admin-report-service.ts
backend/src/v1/types/report-search.ts

Fixes: [GEO-1046](https://finrms.atlassian.net/browse/GEO-1046) and [GEO-1047](https://finrms.atlassian.net/browse/GEO-1047)
New unit tests
---
- [Frontend](https://pay-transparency-pr-749-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-749-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-749-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

feat: GEO-1046 and GEO-1047 - preliminary implementation of dashboard page

---

admin-frontend/src/components/AnnouncementsPage.vue
admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue

Fix accessibility by adding aria-labels
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1138))
---
- [Frontend](https://pay-transparency-pr-756-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-756-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-756-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1138 accessibility announcements missing aria labels

---

admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue
admin-frontend/src/components/announcements/FilterDateRangeTooltip.vue

Fix accessibility announcements filter date range
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1142))
---
- [Frontend](https://pay-transparency-pr-757-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-757-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-757-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1142 accessibility announcements filter date range

---

admin-frontend/src/components/AnnouncementsPage.vue
admin-frontend/src/components/ReportSearchFilters.vue
admin-frontend/src/components/ReportsPage.vue
admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue

Fix announcements page layout
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1150))
---
- [Frontend](https://pay-transparency-pr-761-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-761-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-761-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: geo 1150 fix announcements page layout

---

admin-frontend/src/components/AnnouncementsPage.vue
admin-frontend/src/components/announcements/AnnouncementActions.vue
admin-frontend/src/types/index.ts
admin-frontend/src/utils/constant.js
backend/src/admin-app.ts
backend/src/config/index.ts
backend/src/v1/email-templates/index.ts
backend/src/v1/routes/config-routes.ts
backend/src/v1/routes/config.routes.spec.ts
charts/fin-pay-transparency/templates/configmap.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

Update Expiration email verbiage & Archive confirmation dialogue
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1146))
---
- [Frontend](https://pay-transparency-pr-765-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-765-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-765-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …

fix: geo 1146 Update Expiration email verbiage & Archive confirmation dialogue

---

admin-frontend/Caddyfile
admin-frontend/src/components/AnalyticsPage.vue
admin-frontend/src/components/DashboardPage.vue
admin-frontend/src/components/__tests__/DashboardPage.spec.ts
charts/fin-pay-transparency/charts/admin-frontend/templates/deployment.yaml
charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-pr.yaml
charts/fin-pay-transparency/values.yaml

With the changes in this PR, by default, the admin dashboard and analytics pages won't be accessible.  Users will still be able to navigate to the pages from the sidebar menu and the breadbrumb trail, but the pages themselves will be blank.  
To make these pages visible in a local development environment, developers can add a env.js file to the admin-frontend root folder which contains the following:
```
window.config = {
IS_ADMIN_DASHBOARD_AVAILABLE: 'true',
IS_ADMIN_ANALYTICS_AVAILABLE: 'true',
};
```
For deployments to openshift environments, the values are populated in charts/fin-pay-transparency/values*.yaml
via 'isAdminDashboardAvailable' and 'isAdminAnalyticsAvailable' env vars under the admin-frontend app.  Currently these values are set to 'true' for the PR Sandbox and Dev …

feat: GEO-1140 - added flags to control whether admin dahboard and admin analytics pages are visible

---

admin-frontend/src/components/announcements/AnnouncementForm.vue

https://finrms.atlassian.net/browse/GEO-1151
---
- [Frontend](https://pay-transparency-pr-768-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-768-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-768-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-1151 Fix datepicker button

---

backend/src/v1/routes/announcement-routes.ts
clamav-service/src/app.ts

Allow normal users to add/edit announcement
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1147))
---
- [Frontend](https://pay-transparency-pr-769-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-769-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-769-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: allow normal users to add.edit announcement

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-771-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-771-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-771-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

fix!: updating test pvc size

---

backend/src/v1/middlewares/storage/upload.spec.ts
backend/src/v1/middlewares/storage/upload.ts

Security issue with file upload path
---
- [Frontend](https://pay-transparency-pr-778-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-778-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-778-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: security issue with file upload path

---

backend/src/schedulers/expire-announcements-scheduler.spec.ts
backend/src/schedulers/expire-announcements-scheduler.ts
backend/src/v1/middlewares/validations/index.ts
backend/src/v1/routes/admin-user-invites-routes.spec.ts
backend/src/v1/routes/admin-user-invites-routes.ts
backend/src/v1/routes/analytic-routes.spec.ts
backend/src/v1/routes/analytic-routes.ts
backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/routes/announcement-routes.ts
backend/src/v1/routes/dashboard/announcement-metrics-routes.spec.ts
backend/src/v1/routes/dashboard/announcement-metrics-routes.ts
backend/src/v1/routes/dashboard/index.spec.ts
backend/src/v1/services/admin-user-invites-service.spec.ts
backend/src/v1/services/admin-user-invites-service.ts
backend/src/v1/services/analytic-service.spec.ts
backend/src/v1/services/analytic-service.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/services/scheduler-service.spec.ts
backend/src/v1/services/scheduler-service.ts
backend/src/v1/services/utils-service.ts

Refactor backend services to export an object instead of individual methods
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1152))
---
- [Frontend](https://pay-transparency-pr-784-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-784-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-784-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows …

fix: Geo 1152 code review export objects instead of each method

---

.github/workflows/.deploy.yml
admin-frontend/src/components/AnalyticsPage.vue
admin-frontend/src/utils/constant.js
backend/src/config/index.ts
backend/src/v1/routes/analytic-routes.spec.ts
backend/src/v1/services/analytic-service.spec.ts
backend/src/v1/services/analytic-service.ts
charts/fin-pay-transparency/templates/secret.yaml

https://finrms.atlassian.net/browse/GEO-1121
---
- [Frontend](https://pay-transparency-pr-783-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-783-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-783-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1121 Single analytics powerBi report with error notifications.

---

backend/src/v1/services/employer-service.spec.ts
backend/src/v1/services/employer-service.ts

https://finrms.atlassian.net/browse/GEO-1160
---
- [Frontend](https://pay-transparency-pr-800-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-800-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-800-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1160 Case insensitive employer search

---

admin-frontend/e2e/pages/admin-portal-page.ts
admin-frontend/e2e/pages/announcements/announcements-page.ts
admin-frontend/e2e/pages/reports/search-reports-page.ts
admin-frontend/e2e/reports.spec.ts
admin-frontend/src/components/ReportSearchFilters.vue

Admin report search and locking end to end test
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-870))
---
- [Frontend](https://pay-transparency-pr-801-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-801-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-801-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: geo 870 e2e admin report search and locking end to end test

---

admin-frontend/src/components/EmployersPage.vue

- changed the heading "Search employer" to "Search Employer"
- changed column header "Date of First Log On" to "Date of First Log In"
Fixes # [GEO-1132](https://finrms.atlassian.net/browse/GEO-1132)
---
- [Frontend](https://pay-transparency-pr-808-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-808-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-808-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …

feat: GEO-1132 - admin site - minor changes to wording on Employer Search page

---

charts/fin-pay-transparency/values-prod.yaml

Memory requests and limits for backend service has been bumped to ensure backend service containers are not killed as memory consumption is near current limits defined for the service.
Fixes #  No issue has been raised
This has not been tested yet!
It is being done as a preventive measure to ensure backend pods are not killed because of Out of Memory.
---
- [Frontend](https://pay-transparency-pr-816-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-816-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-816-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in …

chore(resources): Set memory requests and limits for backend

---

charts/fin-pay-transparency/values-pr.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values.yaml

Fixes # [GEO-1141](https://finrms.atlassian.net/browse/GEO-1141)
---
- [Frontend](https://pay-transparency-pr-817-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-817-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-817-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1141 - change env vars to enable admin dashboard and analytics pages in all deployment environments

---

.github/workflows/.deploy.yml
.github/workflows/cd-to-prod-on-workflow-dispatch.yml
.github/workflows/cd-to-test-on-workflow-dispatch.yml
admin-frontend/src/components/Header.vue

---
- [Frontend](https://pay-transparency-pr-828-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-828-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-828-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: deployer to ignore extra semver GEO-1090

---

admin-frontend/src/components/announcements/AnnouncementForm.vue
admin-frontend/src/components/user-management/AddUserButton.vue
admin-frontend/src/components/user-management/__tests__/AddUserButton.spec.ts
backend/src/v1/services/report-calc-service.ts

Fixed some code smells identified by Sonar.  The most significant change involved refactoring a function within AnnouncementForm.vue to reduce its cognitive complexity.
Fixes # [GEO-1219](https://finrms.atlassian.net/browse/GEO-1219)
- Updated existing unit tests.
[GEO-1219]: https://finrms.atlassian.net/browse/GEO-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-842-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-842-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-842-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please …

fix: GEO-1219 - sonar issues

---

admin-frontend/src/components/AnnouncementsPage.vue
admin-frontend/src/components/__tests__/AnnouncementsPage.spec.ts
admin-frontend/src/components/announcements/AnnouncementActions.vue
admin-frontend/src/components/announcements/AnnouncementStatusChip.vue
admin-frontend/src/components/announcements/__tests__/AnnouncementActions.spec.ts
admin-frontend/src/services/__tests__/apiService.spec.ts
admin-frontend/src/services/apiService.ts
admin-frontend/src/store/modules/announcementSearchStore.ts
admin-frontend/src/types/announcements.ts
backend/db/migrations/V1.0.43__change_deleted_to_archived.sql
backend/src/v1/prisma/schema.prisma
backend/src/v1/routes/announcement-routes.spec.ts
backend/src/v1/routes/announcement-routes.ts
backend/src/v1/services/announcements-service.spec.ts
backend/src/v1/services/announcements-service.ts
backend/src/v1/services/error-service.ts
backend/src/v1/types/announcements.ts
frontend/src/types/announcements.ts

https://finrms.atlassian.net/browse/GEO-1185
---
- [Frontend](https://pay-transparency-pr-844-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-844-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-844-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1185 Change status to ARCHIVED instead of DELETED

---

.vscode/tasks.json
backend/db/migrations/V1.0.45__comments.sql

https://finrms.atlassian.net/browse/GEO-1169
---
- [Frontend](https://pay-transparency-pr-866-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-866-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-866-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: GEO-1169 Database comments

---

admin-frontend/src/components/announcements/AnnouncementForm.vue

---
- [Frontend](https://pay-transparency-pr-869-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-869-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-869-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: e2e test

---

charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-pr.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-875-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-875-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-875-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: resource adjustment, remove limits as it is now removed from platform

---

charts/fin-pay-transparency/values-dev.yaml
charts/fin-pay-transparency/values-pr.yaml
charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml
charts/fin-pay-transparency/values.yaml

---
- [Frontend](https://pay-transparency-pr-877-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-877-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-877-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

chore: GEO-1265 remove limits from helm charts

---

charts/fin-pay-transparency/values-prod.yaml
charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-881-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-881-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-881-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

chore: update PROD resources

---

charts/fin-pay-transparency/values-test.yaml

---
- [Frontend](https://pay-transparency-pr-885-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-885-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-885-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: reducing resources(cpu) in TEST from backend and doc gen to allow the cronjobs of crunchy to run which executes backups

---

frontend/package-lock.json

Bumping nanoid version manually, dependabot is not able to access secrets causing backend unit tests to fail.
PR generated by dependabot: https://github.com/bcgov/fin-pay-transparency/tree/dependabot/npm_and_yarn/frontend/nanoid-3.3.8
Bumps [nanoid](https://github.com/ai/nanoid) from 3.3.7 to 3.3.8. 
Testing would be performed via current set of test cases
---
- [Frontend](https://pay-transparency-pr-886-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-886-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-886-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs …

chore(Update Deps): Bump Nanoid version

---

.diagrams/architecture/data-flow-diagrams/pay-transparency-reporting-tool-L1.mermaid

---
- [Frontend](https://pay-transparency-pr-890-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-890-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-890-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …

docs: Updated L1 reporting data flow diagram

---

frontend/src/components/InputForm.vue

https://finrms.atlassian.net/browse/GEO-1270
---
- [Frontend](https://pay-transparency-pr-901-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-901-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-901-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

fix: GEO-1270 Fix order of operations for date loading

---

charts/fin-pay-transparency/values-prod.yaml

https://finrms.atlassian.net/browse/GEO-1272
---
- [Frontend](https://pay-transparency-pr-906-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-906-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-906-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

chore: disable user-error log deletion schedule

---

admin-frontend/package-lock.json
admin-frontend/package.json
frontend/package-lock.json
frontend/package.json

Dependencies have been updated to mitigate security concerns raised via Dependabot and code scanning
- https://github.com/bcgov/fin-pay-transparency/security/dependabot/118 
- https://github.com/bcgov/fin-pay-transparency/security/dependabot/107
Testing would be performed via integration and E2E test cases
---
- [Frontend](https://pay-transparency-pr-911-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-911-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-911-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft mode.  Mark as ready to …

chore(security): update deps to mitigate security risks

---

charts/fin-pay-transparency/values-test.yaml

The change updates the Postgres version in Helm values file for TEST environment after successful major version upgrade
https://finrms.atlassian.net/browse/GEO-1281
---
- [Frontend](https://pay-transparency-pr-936-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-936-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-936-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …

chore(upgrade): update postgres version from 15 to 17

---

admin-frontend/e2e/pages/reports/search-reports-page.ts
admin-frontend/e2e/search-reports.spec.ts
admin-frontend/src/components/ReportSearchFilters.vue
admin-frontend/src/components/__tests__/ReportsSearchFilters.spec.ts
admin-frontend/src/components/dashboard/RecentlySubmittedReports.vue
admin-frontend/src/components/dashboard/RecentlyViewedReports.vue
admin-frontend/src/components/dashboard/__tests__/RecentlySubmittedReports.spec.ts
admin-frontend/src/components/dashboard/__tests__/RecentlyViewedReports.spec.ts
admin-frontend/src/components/reports/ReportActions.vue
admin-frontend/src/components/reports/ReportAdminActionHistoryPanel.vue
admin-frontend/src/store/modules/reportSearchStore.ts
admin-frontend/src/types/reports.ts
backend/src/v1/services/admin-report-service.spec.ts
backend/src/v1/services/admin-report-service.ts
backend/src/v1/types/report-search.ts

---
- [Frontend](https://pay-transparency-pr-961-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-961-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-961-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1280 Withdraw search filter

---

backend/db/migrations/V1.0.49__update_date_reports_views.sql

---
- [Frontend](https://pay-transparency-pr-969-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-969-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-969-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO -1287 Change update_date for the external API

---

admin-frontend/src/components/reports/ReportActions.vue

---
- [Frontend](https://pay-transparency-pr-970-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-970-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-970-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)

feat: GEO-1284 Admin action tooltips
