bcgov/fin-pay-transparency

- backend/src/v1/services/validate-service.spec.ts
- backend/src/v1/services/validate-service.ts
Small refactor.  Validate service had seven different constants specifying column names in the CSV.  We need to reference these from multiple other service-layer files.  To make it easier to import and understand, I moved the constants into a new enum called CSV_COLUMNS.  
No functional changes.
I made a separate pull request for this just because many lines of code were modified for the enum change.  I don't want to overwhelm code reviewers by bundling it with another piece of work.
- existing unit tests were updated to use the new enum.
> moved the seven different column name constants into an enum

- charts/fin-pay-transparency/charts/backend/templates/deployment.yaml
- charts/fin-pay-transparency/charts/backend/templates/pdb.yaml
- charts/fin-pay-transparency/charts/doc-gen-service/templates/deployment.yaml
- charts/fin-pay-transparency/charts/doc-gen-service/templates/pdb.yaml
- charts/fin-pay-transparency/charts/frontend/templates/deployment.yaml
- charts/fin-pay-transparency/charts/frontend/templates/pdb.yaml
- charts/fin-pay-transparency/values-pr.yaml
- charts/fin-pay-transparency/values.yaml
The PR helps in 
1. Distributing pods across multiple worker nodes in HA environment with affinity rules.
2. Making sure there is always minimum available 1 pod during upgrades with PDB.
affinity docs:
https://docs.openshift.com/container-platform/4.14/nodes/scheduling/nodes-scheduler-node-affinity.html#nodes-scheduler-node-affinity-about_nodes-scheduler-node-affinity
pdb docs:
https://docs.openshift.com/container-platform/4.14/nodes/pods/nodes-pods-configuring.html#nodes-pods-pod-disruption-configuring_nodes-pods-configuring
---
- [Frontend](https://pay-transparency-pr-165-frontend.apps.silver.devops.gov.bc.ca)
> feat: pdb and affinity

- backend/src/v1/routes/auth-routes.ts
- backend/src/v1/services/auth-service.spec.ts
- backend/src/v1/services/auth-service.ts
If the IDIM SOAP call fails then the login error page is shown to the user but if the user refreshes the page they are shown the home page. This needs to be solved by redirecting the user to the login page.
**Repro steps:**
- Disconnect the VPN connection to mimic a login fail
- Attempt to log in and verify that you are redirected to the /login-error page
- Open another tab and attempt to visit http://localhost:8081/ and verify that you land on the home page
**Expected behavior:**
When the VPN connection fails, the user should not be allowed to visit the homepage
---
- [Frontend](https://pay-transparency-pr-213-frontend.apps.silver.devops.gov.bc.ca)
> terminate session when failed to get company details

- backend/src/v1/services/report-service.ts
- doc-gen-service/src/templates/report-template-emp-data-summary.html
- doc-gen-service/src/templates/report-template-header.html
- doc-gen-service/src/v1/services/doc-gen-service.spec.ts
- doc-gen-service/src/v1/services/doc-gen-service.ts
move the data constraints to the end of the report (and out of 'explanatory notes')
Fixes # [GEO-275](https://finrms.atlassian.net/browse/GEO-275)
Visual inspection of the report + existing unit tests
---
- [Frontend](https://pay-transparency-pr-248-frontend.apps.silver.devops.gov.bc.ca)
> move-data-constraits

- doc-gen-service/src/v1/services/doc-gen-service.spec.ts
- doc-gen-service/src/v1/services/doc-gen-service.ts
Doc-gen-service: gracefully handle generateReport() when 'chartData' and 'tableData' properties of the submitted reportData are null.
Fixes # [GEO-339](https://finrms.atlassian.net/browse/GEO-339)
New unit test.
---
- [Frontend](https://pay-transparency-pr-250-frontend.apps.silver.devops.gov.bc.ca)
> handle generateReport() when chartData and tableData are null.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/NotFound.vue
- frontend/src/components/__tests__/NotFound.spec.ts
- frontend/src/router.js
- frontend/src/shims-vue.d.ts
- frontend/src/vitest.setup.ts
- frontend/vite.config.js
- frontend/vitest.setup.ts
Adding 404 page and route
- Added unit tests
- Attempt to navigate to a non existing path in the url, and verify that a not found page
- Verify that you are redirected to the dashboard page when clicking on the `Return to dashboard` button
---
- [Frontend](https://pay-transparency-pr-257-frontend.apps.silver.devops.gov.bc.ca)
> adding notfound/404 page

- frontend/src/router.js
When an unauthenticated user navigate to a 404 page, the user should be redirected to the login page
---
- [Frontend](https://pay-transparency-pr-258-frontend.apps.silver.devops.gov.bc.ca)
> require auth when user hits 404 page

- frontend/src/components/Footer.vue
I made a bug in the footer on this page https://dev.paytransparency.fin.gov.bc.ca/token-expired
Footer is too large.
This fixes the issue as seen here https://pay-transparency-pr-263-frontend.apps.silver.devops.gov.bc.ca/token-expired
---
- [Frontend](https://pay-transparency-pr-263-frontend.apps.silver.devops.gov.bc.ca)
> bugfix/Make footer apply to app instead of container.

- backend/src/app.ts
- backend/src/v1/routes/config-routes.ts
- backend/src/v1/routes/config.routes.spec.ts
- frontend/src/common/__tests__/apiService.spec.ts
- frontend/src/common/apiService.ts
- frontend/src/common/types/index.ts
- frontend/src/components/InputForm.vue
- frontend/src/components/__tests__/InputForm.spec.ts
- frontend/src/store/modules/__tests__/config.spec.ts
- frontend/src/store/modules/config.ts
- frontend/vite.config.js
The front end needs to get some config variables from the backend for display. I added a backend endpoint to expose some config variables and consumed them in the front end.
- I added endpoint `/config` to get the `uploadFileMaxSizeBytes` size
- Added a frontend pinia store to manage config data from the API
- Displayed the `uploadFileMaxSizeBytes` in `MB` in the InputForm
---
- [Frontend](https://pay-transparency-pr-262-frontend.apps.silver.devops.gov.bc.ca)
> feat: add endpoint to get config settings and use them in the frontend

- frontend/src/components/PublishedReportPage.vue
On the Published Report screen, moved the existing "Download PDF" button into a floating footer ribbon (so it's always visible when scrolling).  Also added an "Edit this Report" button to the footer ribbon.  Currently "Edit this Report" just redirects back to the InputForm screen without any parameters passed.
Fixes # [GEO-214](https://finrms.atlassian.net/browse/GEO-214)
Visual inspection of the frontend in a browser
---
- [Frontend](https://pay-transparency-pr-273-frontend.apps.silver.devops.gov.bc.ca)
> floating footer for buttons "Download PDF" and "Edit this Report"

- backend/db/migrations/V1.0.16__report_history_locking.sql
Added `is_unlocked` column to the `report_history` table to allow reports to be copied
---
- [Frontend](https://pay-transparency-pr-286-frontend.apps.silver.devops.gov.bc.ca)
> adding is_unlocked column to report_history table

- docker-compose.yml
Fixed an issue preventing the database service from being built.
The issue was caused by a recent commit that removed the Dockerfile for the database service.  Sukanya says instead of the Dockerfile for that service, we can use the postgres:15 image.
Running `podman-compose up --build -d database` now works again!
> fixed a problem with the database service

- backend/src/v1/services/report-service.ts
- frontend/package.json
- frontend/src/common/types/index.ts
- frontend/src/components/Dashboard.vue
- frontend/src/components/InputForm.vue
- frontend/src/components/PublishedReportPage.vue
- frontend/src/components/__tests__/Dashboard.spec.ts
Adding the ability to edit a published report
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-133))
---
- [Frontend](https://pay-transparency-pr-292-frontend.apps.silver.devops.gov.bc.ca)
> add ability to edit a published report

- frontend/src/components/InputForm.vue
- frontend/src/components/__tests__/Dashboard.spec.ts
- frontend/src/router.js
- frontend/src/store/modules/config.ts
Make sure that the max file upload size is always displayed in the input form
---
- [Frontend](https://pay-transparency-pr-293-frontend.apps.silver.devops.gov.bc.ca)
> Make sure that max file upload size is always displayed in the input form

- frontend/package-lock.json
Fixing security issue raised by dependabot caused by an old version of axios in some of our sub dependencies
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-397))
Make sure the build passes
---
- [Frontend](https://pay-transparency-pr-301-frontend.apps.silver.devops.gov.bc.ca)
> fix: security issue: force axios 1.6.7 in a subdependency

- backend/src/v1/services/file-upload-service.spec.ts
- backend/src/v1/services/file-upload-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
Prevent override a published report (older than 30days) for the same date range 
---
- [Frontend](https://pay-transparency-pr-306-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-306-frontend.apps.silver.devops.gov.bc.ca)
> prevent override a report update

- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend/src/v1/routes/external-consumer-routes.spec.ts
- backend/src/v1/routes/external-consumer-routes.ts
- backend/src/v1/services/external-consumer-service.spec.ts
- backend/src/v1/services/external-consumer-service.ts
- backend/src/v1/services/scheduler-service.spec.ts
Enhancing the swagger ui by adding params documentations and better error handling
---
- [Frontend](https://pay-transparency-pr-317-frontend.apps.silver.devops.gov.bc.ca)
> adding date docs, and validations, returning informative errors

- backend/src/schedulers/delete-draft-service-scheduler.ts
Changed to use 'trylock' instead of 'withlock'.
https://finrms.atlassian.net/browse/GEO-456
---
- [Frontend](https://pay-transparency-pr-338-frontend.apps.silver.devops.gov.bc.ca)
> fix: handle-lock-in-scheduler-as-when-it-unlocks-all-the-pods-are-executing-the-function-geo-456

- backend/src/constants/index.ts
- backend/src/v1/services/report-calc-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
- backend/src/v1/services/validate-service.spec.ts
- backend/src/v1/services/validate-service.ts
- frontend/src/components/InputForm.vue
- frontend/src/components/__tests__/InputForm.spec.ts
Calendar must allow users to select up to Two full calendar years in the past, from the current date.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-387))
---
- [Frontend](https://pay-transparency-pr-339-frontend.apps.silver.devops.gov.bc.ca)
> fix: geo 387 input form calendar change allow up to two previous years from current date

- backend/src/v1/services/external-consumer-service.ts
Fix default date range to match all records within the date range
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-463))
Steps to test. 
1.  Publish a a new PT report.
2.  Run SwaggerUI with no filter and verify that the new report_id is displayed.
---
- [Frontend](https://pay-transparency-pr-345-frontend.apps.silver.devops.gov.bc.ca)
> fix: default date range to match all records within the date range

- backend/db/migrations/V1.0.20__add_report_locking_date.sql
- backend/src/config/index.ts
- backend/src/v1/prisma/schema.prisma
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/scheduler-service.spec.ts
- backend/src/v1/services/scheduler-service.ts
- charts/fin-pay-transparency/templates/configmap.yaml
- charts/fin-pay-transparency/values-dev.yaml
- charts/fin-pay-transparency/values-prod.yaml
- charts/fin-pay-transparency/values-test.yaml
- charts/fin-pay-transparency/values.yaml
adding report unlock date and default is unlocked to true
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-474))
---
- [Frontend](https://pay-transparency-pr-354-frontend.apps.silver.devops.gov.bc.ca)
> feat - adding report unlock date and default is unlocked to true

- backend/src/v1/routes/report-routes.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
- frontend/src/common/apiService.ts
- frontend/src/common/types/index.ts
- frontend/src/components/DraftReportPage.vue
Prevent users from updating/overriding a locked report
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-480))
---
- [Frontend](https://pay-transparency-pr-366-frontend.apps.silver.devops.gov.bc.ca)
> fix:  geo 480 im able to override locked published reports

- backend/src/v1/services/report-service.ts
- doc-gen-service/src/templates/report-template-header.html
- doc-gen-service/src/v1/services/doc-gen-service.spec.ts
- doc-gen-service/src/v1/services/doc-gen-service.ts
- frontend/src/components/Dashboard.vue
- frontend/src/components/__tests__/Dashboard.spec.ts
Display reporting year on dashboard table and the generated report
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-462))
Verify that the reporting is displayed in the dashboard and the report
---
- [Frontend](https://pay-transparency-pr-367-frontend.apps.silver.devops.gov.bc.ca)
> feat: Display reporting year on dashboard table and the generated report

- frontend/src/components/InputForm.vue
- frontend/src/components/__tests__/InputForm.spec.ts
prior to 2025, the only available reporting year is the current year.  in 2025 or after both the current year and the previous year are options.
Fixes # [GEO-515](https://finrms.atlassian.net/browse/GEO-515)
New unit tests
---
- [Frontend](https://pay-transparency-pr-401-frontend.apps.silver.devops.gov.bc.ca)
> feat: reporting-year-options

- backend/src/v1/services/validate-service.spec.ts
- backend/src/v1/services/validate-service.ts
Backend now validates reporting year according to the following rule:
- If currentYear is >= 2025 then valid reporting years are [currentYear, currentYear - 1]
- If currentYear is < 2025 then valid reporting years are [currentYear]
New unit tests
---
- [Frontend](https://pay-transparency-pr-404-frontend.apps.silver.devops.gov.bc.ca)
> feat: update reporting year validation on backend

- .github/workflows/.e2e.yml
- .vscode/settings.json
- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend/db/migrations/V1.0.22__report_id_fk_in_history.sql
- backend/src/v1/prisma/schema.prisma
- backend/src/v1/routes/external-consumer-routes.spec.ts
- backend/src/v1/routes/report-routes.ts
- backend/src/v1/services/external-consumer-service.spec.ts
- backend/src/v1/services/external-consumer-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
- frontend/e2e/pages/report.ts
- frontend/e2e/report-generation.spec.ts
- frontend/e2e/utils/edit-report.ts
- frontend/e2e/utils/generate-report.ts
- frontend/src/common/apiService.ts
- frontend/src/components/DraftReportPage.vue
- Refactor report publishing to correctly save the report history
- Including report history to the external API
- 
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-496))
Fixes # ([[issue](https://finrms.atlassian.net/browse/GEO-496)](https://finrms.atlassian.net/browse/GEO-529))
---
- [Frontend](https://pay-transparency-pr-408-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-408-frontend.apps.silver.devops.gov.bc.ca)
> feat: geo 496 backend external include report and calculation history data to the report if it exists

- frontend/src/components/InputForm.vue
made the InputForm's responsive width, the position of the back button, and the width of the 'stepper' consistent with the Draft and Published report screens
Fixes # [GEO-532](https://finrms.atlassian.net/browse/GEO-532)
Visual inspection of the application.
---
- [Frontend](https://pay-transparency-pr-431-frontend.apps.silver.devops.gov.bc.ca)
> fix: input form width

- charts/fin-pay-transparency/values-dev.yaml
- charts/fin-pay-transparency/values.yaml
The PR sandbox and dev environments currently offer 2023 and 2024 as reporting year options.  This PR removes 2023 as an option.  (The 2023 option was only needed for testing, and that testing is now complete.)  
Visual inspection in PR sandbox.
---
- [Frontend](https://pay-transparency-pr-432-frontend.apps.silver.devops.gov.bc.ca)
> feat: reporting year options

- frontend/e2e/pages/page.ts
- frontend/e2e/pages/report.ts
- frontend/e2e/utils/edit-report.ts
@goemen helped me get this to run on windows. There was an issue with the account button being clicked twice in a row.
---
- [Frontend](https://pay-transparency-pr-448-frontend.apps.silver.devops.gov.bc.ca)
> fix: Playwright fix for windows

- frontend/src/components/Footer.vue
https://finrms.atlassian.net/browse/GEO-591
---
- [Frontend](https://pay-transparency-pr-465-frontend.apps.silver.devops.gov.bc.ca)
---
- [Frontend](https://pay-transparency-pr-465-frontend.apps.silver.devops.gov.bc.ca)
- [Analysis Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/a …
> fix: Standard footer design

- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend/src/v1/routes/external-consumer-routes.spec.ts
- backend/src/v1/services/external-consumer-service.spec.ts
- backend/src/v1/services/external-consumer-service.ts
Filter reports based on update date for external API
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-599))
---
- [Frontend](https://pay-transparency-pr-468-frontend.apps.silver.devops.gov.bc.ca)
> fix: Filter reports based on update date for external api

- backend/src/app.ts
Fix for the below.
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (node:_http_outgoing:659:11)
at ServerResponse.header (/app/node_modules/express/lib/response.js:795:10)
at ServerResponse.send (/app/node_modules/express/lib/response.js:175:12)
at ServerResponse.json (/app/node_modules/express/lib/response.js:279:15)
at ServerResponse.send (/app/node_modules/express/lib/response.js:163:21)
at /app/dist/app.js:233:28
at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
at /app/node_modules/express/lib/router/index.js:286:9
at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
--- …
> fix(backend): 500 error scenario handling

- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend/src/v1/routes/external-consumer-routes.spec.ts
- backend/src/v1/services/external-consumer-service.ts
reduce the default and maximum page size for the data returned 
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-599))
---
- [Frontend](https://pay-transparency-pr-481-frontend.apps.silver.devops.gov.bc.ca)
> fix: reduce the default and maximum page size for the data returned 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Dashboard.vue
- frontend/src/components/__tests__/Dashboard.spec.ts
- frontend/src/components/util/ReportsTable.vue
- frontend/src/components/util/__tests__/ReportsTable.spec.ts
Convert dashboard vtable into v-datatable add pagination and other table features.
https://github.com/bcgov/fin-pay-transparency/assets/4842061/f29a6032-da2a-49fc-a6a2-039bfb06e7b3
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-546))
---
- [Frontend](https://pay-transparency-pr-435-frontend.apps.silver.devops.gov.bc.ca)
> feat: add v-datatable to the dashboard reports

- frontend/src/components/Login.vue
Updated the 'Guidance for Preparing Pay Transparency Reports' link on the landing page to point at a new URL with a more up-to-date document.
Fixes # [GEO-618](https://finrms.atlassian.net/browse/GEO-618)
Visual inspection in the application.
[GEO-618]: https://finrms.atlassian.net/browse/GEO-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-487-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …
> feat: updated landing page link to 'Guidance for Preparing Pay Transparency Reports' (pdf)

- backend/src/v1/services/external-consumer-service.ts
- backend/src/v1/services/report-service.ts
https://finrms.atlassian.net/browse/GEO-613
---
- [Frontend](https://pay-transparency-pr-486-frontend.apps.silver.devops.gov.bc.ca)
> fix(backend-external): duplicate results in api

- admin-frontend/src/common/apiService.ts
- admin-frontend/src/store/modules/__tests__/auth.spec.ts
- admin-frontend/src/store/modules/__tests__/codeStore.spec.ts
- admin-frontend/src/store/modules/auth.js
- charts/fin-pay-transparency/charts/backend/templates/service.yaml
Frontend and admin-frontend were sharing the same "local storage" key for their distinct JWT tokens.  I changed the name of the storage key for the admin token so it doesn't interfere with the frontend (and vice versa).
Also fixed a problem with the backend port used for the admin API.
- Existing unit tests have been updated
- Manual test of login for both frontend and admin-frontend
---
- [Frontend](https://pay-transparency-pr-510-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-510-admin-frontend.apps.silver.devops.gov.bc.ca) …
> fix: make frontend and admin-frontend not interfere with each other's local storage tokens

- .github/workflows/.e2e-admin.yml
- .github/workflows/.e2e.yml
- .github/workflows/ci_cd_on_pr_dev_sandbox.yml
- .github/workflows/merge.yml
- backend-external/src/v1/routes/pay-transparency-routes.spec.ts
- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend-external/src/v1/services/pay-transparency-service.spec.ts
- backend-external/src/v1/services/pay-transparency-service.ts
- frontend/e2e/auth.teardown.ts
- frontend/e2e/pages/login.ts
- frontend/e2e/utils/index.ts
Integrate delete reports teardown in the playwright tests.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-567))
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
---
- [Frontend](https://pay-transparency-pr-507-frontend.apps.silver.devops.gov.bc.ca)
---
Deployments, …
> feat: geo 567 integrate delete reports teardown in the playwright tests

- backend-external/package-lock.json
- backend-external/package.json
- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend-external/tests/integration/integration.spec.ts
- backend/src/v1/services/external-consumer-service.spec.ts
- backend/src/v1/services/external-consumer-service.ts
Validate end date is always before today
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-657))
---
- [Frontend](https://pay-transparency-pr-513-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-513-admin-frontend.apps.silver.devops.gov.bc.ca)
> fix: geo 657 validate end date is always before today

- .github/workflows/ci_cd_on_pr_dev_sandbox.yml
---
- [Frontend](https://pay-transparency-pr-514-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-514-admin-frontend.apps.silver.devops.gov.bc.ca)
> fix: remove admin e2e from workflow

- .github/workflows/.e2e.yml
Use fromJson to convert timeout-minutes string to a number
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-702))
---
- [Frontend](https://pay-transparency-pr-524-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-524-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-524-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: use fromJson to convert string to number

- .github/workflows/.e2e.yml
- .github/workflows/merge.yml
1. Remove end-to-end tests from pr merge
---
- [Frontend](https://pay-transparency-pr-529-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-529-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-529-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: remove end-to-end tests from pr merge

- admin-frontend/package.json
- backend-external/package.json
- backend/package.json
- frontend/package.json
https://finrms.atlassian.net/browse/GEO-593
frontend and admin-frontend: added no-vars rule
backend and backend-external: eslint wasn't loading due to typo in config. after fix typo 'var' keyword now flagged
doc-gen-service: no change, 'var' keyword already flagged
---
- [Frontend](https://pay-transparency-pr-530-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-530-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-530-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/analysis.ym …
> fix: fix/enable no-vars eslint

- backend-external/package-lock.json
- backend-external/package.json
- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend-external/tests/integration/integration.spec.ts
- backend/src/v1/services/external-consumer-service.spec.ts
- backend/src/v1/services/external-consumer-service.ts
Using datetime range instead of just date range to filter reports
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-737))
---
- [Frontend](https://pay-transparency-pr-538-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-538-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-538-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …
> fix: use datetime range for external get reports

- admin-frontend/package-lock.json
- admin-frontend/src/components/ReportsPage.vue
- admin-frontend/src/components/__tests__/ReportsPage.spec.ts
- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
- backend/src/v1/routes/admin-report-routes.spec.ts
- backend/src/v1/routes/admin-report-routes.ts
- backend/src/v1/routes/report-routes.ts
- backend/src/v1/services/file-upload-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
Changes to allow the admin-frontend to download a report PDF and open it in a new browser tab.
Fixes # [GEO-629](https://finrms.atlassian.net/browse/GEO-629)
Existing unit tests for backend.
[GEO-629]: https://finrms.atlassian.net/browse/GEO-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-542-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-542-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-542-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> feat: admin view report

- admin-frontend/src/components/ReportSearchFilters.vue
- admin-frontend/src/components/ReportsPage.vue
- admin-frontend/src/store/modules/reportSearchStore.ts
Improvements to the report (search) page, including:
- Default page size is now 100
- Fixed a problem with the locked/unlocked filter
- Data table is auto populated with reports on page load (no need to first click the search button)
---
- [Frontend](https://pay-transparency-pr-543-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-543-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-543-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new images are …
> feat: admin report page improvements

- .github/workflows/.deploy.yml
- backend-external/src/config/index.ts
- backend-external/src/v1/routes/pay-transparency-routes.spec.ts
- backend-external/src/v1/routes/pay-transparency-routes.ts
- backend-external/src/v1/services/pay-transparency-service.spec.ts
- backend-external/src/v1/services/pay-transparency-service.ts
- backend/db/migrations/V1.0.26__error_table.sql
- backend/src/v1/prisma/schema.prisma
- backend/src/v1/routes/external-consumer-routes.spec.ts
- backend/src/v1/routes/external-consumer-routes.ts
- backend/src/v1/routes/file-upload-routes.spec.ts
- backend/src/v1/routes/file-upload-routes.ts
- backend/src/v1/services/error-service.spec.ts
- backend/src/v1/services/error-service.ts
- charts/fin-pay-transparency/charts/backend-external/templates/deployment.yaml
- charts/fin-pay-transparency/templates/secret.yaml
- charts/fin-pay-transparency/values-dev.yaml
- charts/fin-pay-transparency/values-pr.yaml
- charts/fin-pay-transparency/values-prod.yaml
- charts/fin-pay-transparency/values-test.yaml
- charts/fin-pay-transparency/values.schema.json
- charts/fin-pay-transparency/values.yaml
https://finrms.atlassian.net/browse/GEO-698
This PR Creates a new table, stores errors in the DB, and provides an API to retrive the errors.
Still todo is a scheduler to delete old records, and a switch to turn this feature on or off. Those will come later.
---
- [Frontend](https://pay-transparency-pr-551-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-551-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-551-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …
> feat: GEO-698 Save errors in db

- admin-frontend/src/App.vue
- admin-frontend/src/__tests__/App.spec.ts
- admin-frontend/src/components/SideBar.vue
- admin-frontend/src/router.js
- admin-frontend/src/store/modules/__tests__/auth.spec.ts
- admin-frontend/src/store/modules/auth.js
- backend/src/v1/services/admin-auth-service.ts
In the admin frontend, restrict access to pages based on role.  Also hide links from the sidebar if the user doesn't have appropriate permissions for them.
Fixes # [GEO-924](https://finrms.atlassian.net/browse/GEO-924)
---
- [Frontend](https://pay-transparency-pr-559-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-559-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-559-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new images …
> feat: admin app - restrict access to pages based on role

- admin-frontend/src/store/modules/auth.js
- backend/src/admin-app.ts
- backend/src/app.ts
- backend/src/v1/services/utils-service.spec.ts
- backend/src/v1/services/utils-service.ts
- frontend/src/store/modules/auth.js
Description
Using jsonwebtoken to decode token payload instead of atob and json parse token
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-967))
---
- [Frontend](https://pay-transparency-pr-572-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-572-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-572-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> fix: using jsonwebtoken to decode token payload instead of atob and json parse token

- frontend/package-lock.json
Creating a new PR dues to issues with dependabot's PR.
See the original PR for details: https://github.com/bcgov/fin-pay-transparency/pull/570
---
- [Frontend](https://pay-transparency-pr-580-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-580-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-580-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workfl …
> chore(deps-dev): bump ws from 8.17.0 to 8.18.0 in /frontend

- doc-gen-service/package-lock.json
- doc-gen-service/package.json
Bumps [ws](https://github.com/websockets/ws) to 8.18.0 and updates ancestor dependency [puppeteer](https://github.com/puppeteer/puppeteer). These dependencies need to be updated together.
Updates `ws` from 8.17.0 to 8.18.0
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](https://github.com/websockets/ws/compare/8.17.0...8.18.0)
Updates `puppeteer` from 22.10.0 to 22.13.0
- [Release notes](https://github.com/puppeteer/puppeteer/releases)
- [Changelog](https://github.com/puppeteer/puppeteer/blob/main/release-please-config.json)
- [Commits](https://github.com/puppeteer/puppeteer/compare/puppeteer-v22.10.0...puppeteer-v22.13.0)
Recreating this PR because dependabot's PR had issues. Here is the original PR: https://github.com/bcgov/fin-pay-transparency/pull/581
--- …
> chore(deps): bump ws and puppeteer in /doc-gen-service

- admin-frontend/src/components/user-management/AddUserButton.vue
Remove input type from the email text field to prevent email validation tooltip
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-973))
---
- [Frontend](https://pay-transparency-pr-596-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-596-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-596-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workfl …
> fix: remove input type from the email text field

- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/services/admin-report-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
Several "event" dates (update_date, report_unlock_date, admin_modified_date) saved to the pay_transparency_report table were being saved with the incorrect timezone. Corrected the code to save these with the UTC timezone.
Fixes # [GEO-988](https://finrms.atlassian.net/browse/GEO-988)
Updated existing tests.  Added new tests.
---
- [Frontend](https://pay-transparency-pr-604-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-604-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-604-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft mode.  Mark as ready …
> fix: GEO-988 - use UTC timezone for dates saved to the pay_transparency_reports table

- backend/src/v1/services/external-consumer-service.ts
https://finrms.atlassian.net/browse/GEO-619
Removed the Revision sort as Update_Date is now being updated. Locally JSON results are the same now that Update_Date is updated with a report status change. Needs to be tested with DEV/TEST data.
---
- [Frontend](https://pay-transparency-pr-608-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-608-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-608-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new …
> fix: remove-revision-from-the-sort-of-get-in-external-consumer-api-GEO-619

- backend/src/v1/services/external-consumer-service.ts
- frontend/src/components/util/ReportsTable.vue
https://finrms.atlassian.net/browse/GEO-1003
Hid the Items Per Page using CSS : display: none !important
Set ItemsPerPage to 3. 
---
- [Frontend](https://pay-transparency-pr-612-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-612-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-612-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …
> fix: public-facing-app-previous-reports-dashboard-GEO-1003

- admin-frontend/src/App.vue
- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/components/__tests__/AnnouncementsPage.spec.ts
- backend/db/sample-data/generate_fake_announcements.sql
On the admin app's "announcements" page:
- The title of each announcement shown in the search results is now clickable.  Clicking brings up a dialog with the description.
- Each search result now has a checkbox beside it.
- A "Delete" button was added, and it's only enabled when there are selected announcements
Fixes # [GEO-861](https://finrms.atlassian.net/browse/GEO-861)
New unit tests
---
- [Frontend](https://pay-transparency-pr-633-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-633-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-633-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft …
> feat: GEO-861 admin announcements - search results are selectable and clickable

- admin-frontend/src/App.vue
- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/components/__tests__/AnnouncementsPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementActions.vue
- admin-frontend/src/components/announcements/AnnouncementStatusChip.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementActions.spec.ts
- admin-frontend/src/components/announcements/__tests__/AnnouncementSearchFilters.spec.ts
- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
- admin-frontend/src/store/modules/announcementSearchStore.ts
- admin-frontend/src/types/announcements.ts
- backend/db/sample-data/generate_fake_announcements.sql
- backend/src/v1/services/announcements-service.ts
Support delete of multiple selected announcements (via the delete button at the bottom of the announcements page), and support delete of a single announcement from the 'action' button on each row of the data table.
Delete announcement support was added to the backend API in a previous PR. This PR is mainly for the frontend delete-related work (although it includes one minor bug fix to the API.)
Fixes # [GEO-1005](https://finrms.atlassian.net/browse/GEO-1005)
New unit tests
---
- [Frontend](https://pay-transparency-pr-641-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-641-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API …
> feat: GEO-1005 admin app - delete announcements (two ways)

- admin-frontend/src/components/AddAnnouncementPage.vue
- admin-frontend/src/components/EditAnnouncementPage.vue
- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/store/modules/__tests__/announcementSelectionStore.spec.ts
- admin-frontend/src/store/modules/announcementSelectionStore.ts
- admin-frontend/src/types/announcements.ts
Admin app - Add/Edit announcement - Save button is disabled until preview is activated.  Also fixed a bug that caused edited announcements to show up twice in the preview area.
Fixes # [GEO-869](https://finrms.atlassian.net/browse/GEO-869)
updated existing unit tests
---
- [Frontend](https://pay-transparency-pr-656-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-656-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-656-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis Workflow](https://github.com/bcgov/fin-pay-transparency/actions/workflows/analysis. …
> feat: admin announcement preview updates

- admin-frontend/src/components/AddAnnouncementPage.vue
- backend/src/v1/prisma/schema.prisma
Ensure announcement is selectable after add
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1072))
---
- [Frontend](https://pay-transparency-pr-698-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-698-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-698-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO 1072 ensure newly added announcement is selectable

- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/components/__tests__/AnnouncementsPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementActions.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementActions.spec.ts
Fixes # [GEO-1075](https://finrms.atlassian.net/browse/GEO-1075)
Updated unit tests
---
- [Frontend](https://pay-transparency-pr-699-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-699-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-699-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-1075 - admin app - renamed 'delete' action to 'archive'

- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/AnnouncementItem.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementForm.spec.ts
- admin-frontend/src/components/announcements/__tests__/AnnouncementItem.spec.ts
- admin-frontend/src/types/announcements.ts
- frontend/src/components/announcements/AnnouncementItem.vue
- frontend/src/components/announcements/__tests__/AnnouncementItem.spec.ts
Improved the presentation of resource ATTACHMENT links within admin _announcement preview_ and within updates shown on the public site _dashboard_.  ATTACHMENT resources are now presented the same as LINK resources.
Fixes # [GEO-1084](https://finrms.atlassian.net/browse/GEO-1084)
existing tests
---
- [Frontend](https://pay-transparency-pr-711-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-711-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-711-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> feat: GEO-1084 announcement resource link presentation

- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/AttachmentResource.vue
- admin-frontend/src/store/modules/announcementSelectionStore.ts
- backend/src/v1/routes/announcement-routes.ts
- backend/src/v1/services/announcements-service.spec.ts
- backend/src/v1/services/announcements-service.ts
- frontend/playwright.config.ts
Implement display mode for file attachment on announcement edit
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1086))
---
- [Frontend](https://pay-transparency-pr-710-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-710-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-710-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: geo 1086 implement display mode for file attachment on edit

- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementForm.spec.ts
In the admin app:
- Add/edit announcement now makes the "preview" panel always visible.  No need to click a "preview" button to see it.
- Replace the "Draft" and "Published" radio button labels with "chips" for visual consistency with the main Announcements page.
Fixes # [GEO-1095](https://finrms.atlassian.net/browse/GEO-1095), [GEO-1102](https://finrms.atlassian.net/browse/GEO-1102)
Updated existing unit tests
---
- [Frontend](https://pay-transparency-pr-716-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-716-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-716-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please …
> feat: GEO-1095 - admin announcement preview always visible

- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/utils/__tests__/date.spec.ts
- admin-frontend/src/utils/date.ts
- backend/db/migrations/V1.0.38__update_built_in_announcement.sql
- backend/db/migrations/V1.0.39__update_built_in_announcement.sql
Admin announcements page: Updated the display of "Publish on" and "Expires on" dates to appear in the local timezone.  Also added the time which now appears below the dates.
Fixes # [GEO-1096](https://finrms.atlassian.net/browse/GEO-1096)
New unit tests
---
- [Frontend](https://pay-transparency-pr-714-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-714-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-714-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After …
> fix: GEO-1096 - admin - display announcement dates in local timezone

- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/LinkResource.vue
- admin-frontend/src/types/announcements.ts
Create a link display in the announcement edit form
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1089))
---
- [Frontend](https://pay-transparency-pr-717-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-717-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-717-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: geo 1089 announcement link display and edit mode form

- backend/src/v1/services/report-service.ts
- doc-gen-service/src/v1/services/doc-gen-service.spec.ts
- doc-gen-service/src/v1/services/doc-gen-service.ts
- frontend/src/common/types/index.ts
- frontend/src/components/util/ReportsTable.vue
- frontend/src/components/util/__tests__/ReportsTable.spec.ts
Two changes: 
1. A recent renovate PR upgraded puppeteer from v22.13.0 to v23.0.0.  The new puppeteer introduced a breaking change to the PDF export function.  It now returns a byte array instead of a Buffer.  This PR converts the byte array returned by Puppeteer back into the Buffer, which is expected by the pay transparency code.
2. The "submission date" shown for reports on the public site dashboard now comes from 'updated_date' (instead of 'created date)
Fixes # [GEO-1114](https://finrms.atlassian.net/browse/GEO-1114)
new unit test
---
- [Frontend](https://pay-transparency-pr-719-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-719-admin-frontend.apps.silver.devops.gov.bc.ca)
- …
> fix: update doc-gen-service to support puppeteer v23.x.x

- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementForm.spec.ts
https://finrms.atlassian.net/browse/GEO-1105
https://finrms.atlassian.net/browse/GEO-1110
---
- [Frontend](https://pay-transparency-pr-718-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-718-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-718-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> feat: GEO-1105 Display limit for Url and other fields

- backend/db/migrations/V1.0.40__remove_announcement_resource_history_foreign_keys.sql
- backend/src/v1/prisma/schema.prisma
Add ability to delete announcement resource.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1117))
---
- [Frontend](https://pay-transparency-pr-721-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-721-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-721-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: geo 1117 unable to delete link

- admin-frontend/src/components/announcements/AnnouncementActions.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementActions.spec.ts
- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
- backend/src/v1/routes/announcement-routes.spec.ts
- backend/src/v1/routes/announcement-routes.ts
- backend/src/v1/services/announcements-service.spec.ts
- backend/src/v1/services/announcements-service.ts
The code changes in this commit add error handling for the case when the retrieval of an announcement fails. When the `editAnnouncement` function is called, it now makes an API request to retrieve the announcement using the `getAnnouncement` method from the `ApiService`. If the retrieval is successful, the announcement is set in the `announcementSelectionStore` and the user is redirected to the edit announcement page. However, if the retrieval fails, an error message is displayed using the `NotificationService`.
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1085))
---
- [Frontend](https://pay-transparency-pr-724-frontend.apps.silver.devops.gov.bc.ca)
- [Admin …
> fix: Fetch announcement with the edit button is clicked

- backend/src/v1/services/admin-user-invites-service.ts
- backend/src/v1/services/file-upload-service.spec.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
- Fixed an timezone problem related to the expiry date of pending user invitations on the admin site.
- Removed a backend function in report-service that's no longer needed (it contained a suspicious datetime usage, but rather than fix the usage, it made more sense to remove the function).
Fixes # [GEO-1098](https://finrms.atlassian.net/browse/GEO-1098)
---
- [Frontend](https://pay-transparency-pr-725-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-725-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-725-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft mode.  Mark as …
> fix: GEO-1098 datetime cleanups

- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
1. Change label from Publish On to Active On
1. Disable Active On when editing a published report
1. Expires On Date cannot be in the past
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1113))
---
- [Frontend](https://pay-transparency-pr-728-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-728-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-728-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …
> fix: Update label from 'Publish On' to 'Active On' in AnnouncementsPage and Announcement Form

- backend/src/v1/services/announcements-service.spec.ts
- backend/src/v1/services/announcements-service.ts
https://finrms.atlassian.net/browse/GEO-888
---
- [Frontend](https://pay-transparency-pr-743-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-743-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-743-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-888 Change announcement expiry email to 14 days (10 business days)

- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
Set No Expiry checkbox to true if it was previously published with no expiry date
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1133))
---
- [Frontend](https://pay-transparency-pr-745-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-745-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-745-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/wor …
> fix: Set No Expiry checkbox to true if it was previously published with no expiry date

- charts/fin-pay-transparency/values-dev.yaml
- charts/fin-pay-transparency/values-prod.yaml
- charts/fin-pay-transparency/values-test.yaml
- charts/fin-pay-transparency/values.yaml
Testing of this feature is done in Dev, so we don't need daily email spam.
---
- [Frontend](https://pay-transparency-pr-750-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-750-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-750-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> feat: disable announcement expiry notifications in dev

- admin-frontend/src/components/announcements/AnnouncementForm.vue
- backend/src/v1/middlewares/authorization/authenticate-admin.spec.ts
- backend/src/v1/middlewares/authorization/authenticate-admin.ts
- backend/src/v1/middlewares/validations/index.ts
- backend/src/v1/routes/announcement-routes.spec.ts
- backend/src/v1/routes/announcement-routes.ts
- frontend/package-lock.json
- frontend/src/common/__tests__/apiService.spec.ts
- frontend/src/common/apiService.ts
- frontend/src/types/announcements.ts
Problem: The frontend (frontend/src/common/apiService.ts) has the ability to query any status from the announcement table. Currently it specifies that only published results should be shown, but a malicious user could inject some JavaScript in this page to show expired, deleted, or draft statuses. This is because the frontend and admin-frontend share the same route (backend/src/v1/routes/announcement-routes.ts) so anything that the admin-frontend can do, so can the frontend.
Solution: I added some logic in the backend route that if the request is coming from the public site, then it will overwrite the 'filters' and 'sort' part of the query preventing public users from having access to those.
Alternative: an alternative way of handling this would be to create a new announcement-route just …
> fix: fix for frontend announcement having access to ALL states

- admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue
- backend/src/v1/services/announcements-service.ts
https://finrms.atlassian.net/browse/GEO-1149
https://finrms.atlassian.net/browse/GEO-1151
---
- [Frontend](https://pay-transparency-pr-763-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-763-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-763-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: Fix active_on if announcement is already published and fix datepicker buttons

- admin-frontend/src/components/DashboardPage.vue
- admin-frontend/src/components/dashboard/PublicAnnouncements.vue
- admin-frontend/src/components/dashboard/__tests__/PublicAnnouncements.spec.ts
- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
- admin-frontend/src/store/modules/__tests__/dashboardMetricsStore.spec.ts
- admin-frontend/src/store/modules/dashboardMetricsStore.ts
- admin-frontend/src/utils/constant.js
- backend/src/v1/services/code-service.ts
Integrate announcement metrics API with dashboard panel
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1049))
---
- [Frontend](https://pay-transparency-pr-773-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-773-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-773-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> feat: geo 1049 dashboard public announcements panel

- admin-frontend/src/components/announcements/AnnouncementItem.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementItem.spec.ts
- frontend/src/components/announcements/AnnouncementItem.vue
- frontend/src/components/announcements/__tests__/AnnouncementItem.spec.ts
Display error snack bar when download file fails
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1088))
---
- [Frontend](https://pay-transparency-pr-774-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-774-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-774-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO 1088 display error snackbar when download file fails

- admin-frontend/src/components/__tests__/EditAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/AnnouncementItem.vue
- admin-frontend/src/components/announcements/AttachmentResource.vue
- admin-frontend/src/components/announcements/__tests__/AttachmentResource.spec.ts
- admin-frontend/src/constants/index.ts
- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
- backend/src/v1/routes/announcement-routes.ts
Fix: Display error message when download fails
Fix: disappearing file on edit save
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1088))
---
- [Frontend](https://pay-transparency-pr-776-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-776-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-776-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge Workflow](https://github.com/bcgov/fin-pay-transparency/actions/wo …
> fix: GEO-1088 and GEO 1153 Display error message when download fails and fix disappearing file on update

- admin-frontend/src/services/__tests__/apiService.spec.ts
- admin-frontend/src/services/apiService.ts
#Description
Trim announcement text fields
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1158))
---
- [Frontend](https://pay-transparency-pr-779-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-779-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-779-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: trim announcement text fields

- admin-frontend/src/components/announcements/AnnouncementForm.vue
Fix textarea to include new line in characters count
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1158))
---
- [Frontend](https://pay-transparency-pr-781-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-781-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-781-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: geo 1158 fix textarea to correctly count characters

- admin-frontend/src/components/dashboard/NumSubmissionsInYear.vue
- admin-frontend/src/components/dashboard/RecentlySubmittedReports.vue
- admin-frontend/src/components/dashboard/RecentlyViewedReports.vue
- admin-frontend/src/components/dashboard/ReportsWidget.vue
Minor tweaks to the admin dashboard:
- the 'recently viewed' and 'recently submitted' tables now show times (not just dates)
- column widths in the 'recently viewed' and 'recently submitted' tables are consistent
- the 'number of reports submitted in the current reporting year' widget doesn't shown the current reporting year while loading
Fixes # [GEO-579](https://finrms.atlassian.net/browse/GEO-579)
Visual inspection.
---
- [Frontend](https://pay-transparency-pr-792-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-792-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-792-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs) …
> feat: GEO-579 - admin dashboard tweaks

- admin-frontend/e2e/announcements.spec.ts
- admin-frontend/e2e/dashboard.spec.ts
- admin-frontend/e2e/pages/admin-portal-page.ts
- admin-frontend/e2e/pages/dashboard.ts
- admin-frontend/e2e/pages/reports/search-reports-page.ts
- admin-frontend/e2e/pages/user-management/user-management-page.ts
- admin-frontend/e2e/user-management.spec.ts
- admin-frontend/src/components/EmployersPage.vue
- admin-frontend/src/components/ReportSearchFilters.vue
- admin-frontend/src/components/ReportsPage.vue
- admin-frontend/src/components/dashboard/RecentlySubmittedReports.vue
- admin-frontend/src/components/dashboard/RecentlyViewedReports.vue
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1175))
---
- [Frontend](https://pay-transparency-pr-806-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-806-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-806-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> feat:  geo 821/1174/1175 - e2e and change company name to employer name throughout admin portal

- admin-frontend/e2e/announcements.spec.ts
- admin-frontend/e2e/employer-search.spec.ts
- admin-frontend/e2e/pages/employer-search/employer-search-page.ts
- admin-frontend/e2e/user-management.spec.ts
- admin-frontend/e2e/utils/index.ts
- admin-frontend/src/components/AnnouncementsPage.vue
- admin-frontend/src/components/EmployersPage.vue
- admin-frontend/src/components/ReportSearchFilters.vue
- admin-frontend/src/components/ReportsPage.vue
- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/AnnouncementSearchFilters.vue
Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1176))
---
- [Frontend](https://pay-transparency-pr-811-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-811-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-811-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: geo 1176 for consistency we should be capitalizing field names throughout the admin portal

- backend/src/v1/middlewares/storage/upload.ts
I only changed the name of the file that gets uploaded, nothing else.
Testing steps:
1. Create new announcement from the Admin Portal and upload a file: https://pay-transparency-pr-812-admin-frontend.apps.silver.devops.gov.bc.ca/announcements
2. View the announcement form the Frontend: https://pay-transparency-pr-812-frontend.apps.silver.devops.gov.bc.ca/dashboard
3. Click on the attachment link. It downloads as the link name, and it doesn't download as the filename which was stored.
Note that the announcement preview in the Admin Portal behaves differently that the actual announcement in the frontend.
---
- [Frontend](https://pay-transparency-pr-812-frontend.apps.silver.devops.gov.bc.ca)
- [Admin …
> fix: GEO-1186 Store file with a uuid to prevent overwriting

- frontend/e2e/pages/generate-report.ts
- frontend/src/components/InputForm.vue
- frontend/src/main.js
- renamed the submit button to "Generate Draft Report"
- Added a sentence below the button which says: "Your CSV file and draft report will not be shared with the B.C. Government."
Fixes # [GEO-1173](https://finrms.atlassian.net/browse/GEO-1173)
Visual inspection of UI.  Updated e2e tests to recognize the new button label.
---
- [Frontend](https://pay-transparency-pr-814-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-814-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-814-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> feat: GEO-1173 - input form - explanatory sentence and renamed submit button

- admin-frontend/src/components/ReportSearchFilters.vue
- admin-frontend/src/components/__tests__/ReportsSearchFilters.spec.ts
- admin-frontend/src/components/dashboard/RecentlySubmittedReports.vue
- admin-frontend/src/components/dashboard/RecentlyViewedReports.vue
- admin-frontend/src/store/modules/reportSearchStore.ts
- admin-frontend/src/types/reports.ts
- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/types/report-search.ts
Admin portal changes:
- Dashboard page: removed the 'sort arrows' from the column header in both tables ("recently submitted" and "recently viewed")
- Report Search page: Updated the "submission date" filter to map to the "create_date" column (instead of the update_date column).  This makes it consistent with how the term "submission date" is used elsewhere on the page and in the app.
Fixes # [GEO-1190](https://finrms.atlassian.net/browse/GEO-1190) and [GEO-1191](https://finrms.atlassian.net/browse/GEO-1191)
New unit tests.  Updated existing unit tests.
---
- [Frontend](https://pay-transparency-pr-819-frontend.apps.silver.devops.gov.bc.ca)
- [Admin …
> fix: GEO-1190 and GEO-1191 - admin report search and dashboard page fixes

- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/services/admin-report-service.ts
- backend/src/v1/services/report-service.spec.ts
- backend/src/v1/services/report-service.ts
Fixes # [GEO-1194](https://finrms.atlassian.net/browse/GEO-1194)
Updated existing unit tests
---
- [Frontend](https://pay-transparency-pr-821-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-821-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-821-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-1194 - admin tool - lock/unlock no longer clobbers calculated data 

- admin-frontend/src/components/ReportSearchFilters.vue
- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/services/admin-report-service.ts
- backend/src/v1/services/announcements-service.spec.ts
- backend/src/v1/services/announcements-service.ts
- backend/src/v1/services/utils-service.spec.ts
- backend/src/v1/services/utils-service.ts
Fixes # [GEO-1198](https://finrms.atlassian.net/browse/GEO-1198)
New unit tests
[GEO-1198]: https://finrms.atlassian.net/browse/GEO-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-822-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-822-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-822-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new images are …
> fix: GEO-1198 report and announcement searches convert filter dates into UTC timezone

- backend/src/external/services/s3-api.ts
https://finrms.atlassian.net/browse/GEO-1007
Fixed a crash in the schedule that happens when there are no errors, and the code tries to loop through the errors anyways r.Errors.forEach() resulting in a crash.
---
- [Frontend](https://pay-transparency-pr-841-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-841-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-841-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Merge …
> fix: GEO-1007 s3 now reports deleted objects

- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/services/admin-report-service.ts
Fixes # [GEO-1213](https://finrms.atlassian.net/browse/GEO-1213)
New unit test
---
- [Frontend](https://pay-transparency-pr-843-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-843-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-843-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-1213 - admin tool - submission date in search reports csv now corresponds to 'create_date'

- backend/package-lock.json
- backend/package.json
- backend/src/config/index.ts
- backend/src/v1/services/validate-service.spec.ts
- backend/src/v1/services/validate-service.ts
Added two new validation rules to are applied to any rich text fields included in submissions:
- Each rich text value must have fewer than 100 paragraphs.
- If the rich text has any lists, each list must contain fewer than 50 bullet points.
Both limits are configurable with environment variables.
These limits prevent situations that would make it complicated to organize the report content into pages.  
Fixes # [GEO-1166](https://finrms.atlassian.net/browse/GEO-1166)
New unit tests
[GEO-1166]: https://finrms.atlassian.net/browse/GEO-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-848-frontend.apps.silver.devops.gov.bc.ca)
- …
> feat: GEO-1166 - added additional input validation for report rich text input

- admin-frontend/Caddyfile
- admin-frontend/src/components/AnalyticsPage.vue
- admin-frontend/src/components/DashboardPage.vue
Fixes # [GEO-1189](https://finrms.atlassian.net/browse/GEO-1189)
[GEO-1189]: https://finrms.atlassian.net/browse/GEO-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-857-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-857-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-857-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- …
> feat: GEO-1189 - removed flags allowing dashboard and analytics pages to be disabled

- admin-frontend/src/components/announcements/AnnouncementForm.vue
- admin-frontend/src/components/announcements/__tests__/AnnouncementForm.spec.ts
This fix prevents users from receiving a not-very-descriptive error messages if they edit and try saving an expired announcement without first choosing a status of 'DRAFT' or 'PUBLISHED'.
Fixes # [GEO-1239](https://finrms.atlassian.net/browse/GEO-1239)
- New unit test
[GEO-1239]: https://finrms.atlassian.net/browse/GEO-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-861-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-861-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API …
> fix: GEO-1239 - edit expired announcement now has default 'save as' status of 'DRAFT'

- admin-frontend/src/components/__tests__/AddAnnouncementPage.spec.ts
- admin-frontend/src/components/announcements/AnnouncementForm.vue
https://finrms.atlassian.net/browse/GEO-1257
---
- [Frontend](https://pay-transparency-pr-867-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-867-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-867-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-1257 Missing error message when uploading attachment

- admin-frontend/src/App.vue
- admin-frontend/src/components/announcements/AnnouncementForm.vue
Adjusted the style of the vue-datepicker components in the admin tool.  It now matches the style of other vuetify components around it.
Fixes # [GEO-1129](https://finrms.atlassian.net/browse/GEO-1129)
- visual inspection
[GEO-1129]: https://finrms.atlassian.net/browse/GEO-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-870-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-870-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-870-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft mode.  Mark as ready to …
> fix: GEO-1129 adjust vue-datepicker style to match other vuetify components

- backend/src/v1/routes/announcement-routes.spec.ts
- backend/src/v1/types/announcements.ts
Fixes # [GEO-1262](https://finrms.atlassian.net/browse/GEO-1262)
Updated an existing unit test
[GEO-1262]: https://finrms.atlassian.net/browse/GEO-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-872-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-872-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-872-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new …
> fix: GEO-1262 - save announcements in which plain text description length <= 2000 chars, but rich text is > 2000 chars.

- backend/src/v1/middlewares/storage/upload.ts
Fixes # [GEO-1259](https://finrms.atlassian.net/browse/GEO-1259) and [this security issue](https://github.com/bcgov/fin-pay-transparency/security/code-scanning/80)
[GEO-1259]: https://finrms.atlassian.net/browse/GEO-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- [Frontend](https://pay-transparency-pr-883-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-883-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-883-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
Please create PRs in draft mode.  Mark as …
> fix: GEO-1259 - create read stream from a verified path string

- .vscode/fin-pay-transparency.code-workspace
- .vscode/launch.json
- .vscode/tasks.json
- admin-frontend/eslint.config.mjs
- admin-frontend/package-lock.json
- admin-frontend/package.json
- backend-external/eslint.config.mjs
- backend-external/package-lock.json
- backend-external/package.json
- backend/eslint.config.mjs
- backend/package-lock.json
- backend/package.json
- clamav-service/eslint.config.mjs
- clamav-service/package-lock.json
- clamav-service/package.json
- doc-gen-service/eslint.config.mjs
- doc-gen-service/package-lock.json
- doc-gen-service/package.json
- docker-compose.yml
- frontend/eslint.config.mjs
- frontend/package-lock.json
- frontend/package.json
https://finrms.atlassian.net/browse/GEO-1263
---
- [Frontend](https://pay-transparency-pr-887-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-887-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-887-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> chore: GEO-1263 eslint 9 settings

- .vscode/fin-pay-transparency.code-workspace
- backend-external/.gitignore
- backend/.gitignore
- doc-gen-service/.gitignore
- frontend/src/components/__tests__/InputForm.spec.ts
With the new year, one of the tests started failing because it had hard-coded last year (2024) into it's test. Updated the test to dynamically load the current year which aligns with the tests that use the current year.
Also, update .gitignore so that when searching in vscode multi-root projects, the 'coverage' directory is properly ignored.
---
- [Frontend](https://pay-transparency-pr-888-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-888-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-888-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> test: fix broken test due to the new year

- charts/fin-pay-transparency/values-prod.yaml
PVC size for PostgreSQL crunchy cluster has been increased for production environment. PVC was filled up causing one of the cluster member to fail.
Resource increment for crunchy cluster.
---
- [Frontend](https://pay-transparency-pr-891-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-891-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-891-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
After merge, new images are …
> fix(resources): Increment PVC size for crunchy instances

- .github/workflows/pr-validate.yml
- charts/fin-pay-transparency/values-dev.yaml
- charts/fin-pay-transparency/values-prod.yaml
- charts/fin-pay-transparency/values-test.yaml
- charts/fin-pay-transparency/values.yaml
As per suggestions seen in PostgreSQL logs to increment max_wal_size because checkpoints were happening too frequently.
---
- [Frontend](https://pay-transparency-pr-927-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-927-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-927-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> chore(config): update values file with incremented max_wal_size

- charts/fin-pay-transparency/charts/crunchy-postgres/templates/PostgresCluster.yaml
A recent OpenShift platform change caused crunchy cluster to fail because of OpenShift security context compatibility.
https://finrms.atlassian.net/browse/GEO-1279 
Changes have been tested as crunchy cluster is functional after making the changes which was non-functional before the changes.
---
- [Frontend](https://pay-transparency-pr-929-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-929-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-929-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
- [Analysis …
> chore(fix): Add openshift security context flag

- backend/src/v1/services/admin-report-service.spec.ts
- backend/src/v1/services/admin-report-service.ts
---
- [Frontend](https://pay-transparency-pr-962-frontend.apps.silver.devops.gov.bc.ca)
- [Admin Frontend](https://pay-transparency-pr-962-admin-frontend.apps.silver.devops.gov.bc.ca)
- [Backend external API console](https://pay-transparency-pr-962-backend-external.apps.silver.devops.gov.bc.ca/api/V1/docs)
> fix: GEO-1280 Lock status missing in history
